### ISSUE TITLE
[HELP] LSP Server with monaco

### ISSUE THREAD

**Issue by pawansingh00** [python-lsp/python-lsp-server#105]
Hi,

Can anybody help me in Setting it up with -- Monaco Editor.
I am using the following this -- https://github.com/microsoft/monaco-editor/issues/833#issuecomment-393944332
for the same, but its not working out.

Can somebody please confirm on how to start this -- **pyls** ?

Thanks,
Pawan

**Comment by lieryan** [comment]
The executable for python-lsp-server is `pylsp` not `pyls`. 

`pyls` is for Palantir's `python-language-server`, the original, unmaintained project that `python-lsp-server` is based on.

**Comment by pawansingh00** [comment]
@lieryan  Thanks for confirming on the executable.
Still, doesn't seem to work with -- https://github.com/microsoft/monaco-editor/issues/833#issuecomment-393944332

Any pointer on how to use -- `pylsp` any one running exaple is fine.

**Comment by eranif** [comment]
Nothing special is the setup, for me, in my IDE, I just added this line:

```
C:\msys64\mingw64\bin\python3.exe -m pylsp
```
and it just works...

The IDE launches `pylsp` server and captures its `stdout` and `stdin` (for communication)
If its not working for you - I am guessing that the problem is within your IDE/Editor. Try to capture the log of your editor and try to debug the protocol exchange (especially the `initialize` and `initialized` requests)

**Comment by npradeep357** [comment]
@pawansingh00 sis you integrate monaco-language-client from typefox? I did and it worked for me... did you change the line mentioned in the linked comment? 
Also, pylsp does not have websockets support... You need to create a websockets server on top of pylsp IO or TCP and then connect your monaco language client to this webosckets server...

**Comment by pawansingh00** [comment]
@npradeep357 Following the linked comment din't work for me.
Though I have got my use case working using this -- https://github.com/ycm-core/ycmd

**Comment by pplonski** [comment]
Hi, I've integrated monaco editor with pylsp in electron app . Here you have working example https://github.com/pplonski/electron-monaco-python-lsp However there are still some issues that need to be fixed.

**Comment by npradeep357** [comment]
Hey @pawansingh00, i created pr for web sockets in built support  in pylsp.

#128 is the one which have ws support. You can refe to the source code linked in the PR.

You can use that version and run the pylsp using below command. Then monanco can directly connect to it with configured ws url.

`pylsp --ws --host host\ip --port port`

Hope this helps.

**Comment by pawansingh00** [comment]
@npradeep357 
Thanks, looks cool, sure will check it out and update.

I am closing this as I have got my use case covered using this -- https://github.com/ycm-core/ycmd
Which uses -- Jedi-based completer for semantic completion for Python.

Thank you all for your valuable helps and inputs.
