### ISSUE TITLE
Websockets built-in support

### ISSUE THREAD

**Issue by npradeep357** [python-lsp/python-lsp-server#117]
Hi, I got a use case where I have to put up a websockets server on top of PYLSP. 
Will there be any support for Websockets in future?

I'm trying to add one on my own atleast for my use-case but not able to understand the message flow structure. Can you provide help on how the messaging flow happens.

Main problem is: A/c to web sockets spec, there can be 'n' number of connections which can individually be a separate LSP session that means there should be 'n' PYLSP processes if using IO server. 

I'm trying to setup 'n' PYLSP objects in a single process for 'n' web sockets connections. Is there a document on how the 'class PythonLSPServer' works.

Thank you in advance.

**Comment by ccordoba12** [comment]
> Will there be any support for Websockets in future?

No, we don't have plans to do that.

> Can you provide help on how the messaging flow happens.

I don't know how it works, sorry. 

> Is there a document on how the 'class PythonLSPServer' works.

No, there isn't, sorry.

**Comment by npradeep357** [comment]
Hi @ccordoba12 or the authors, as mentioned in my previous comment, i was able to create web sockets service on top of pylsp. It was able to serve multiple ws sessions on a single process with each session with Pylsp instance being sandboxed to itself.

But I need suggestions if this is valid and if it is adhering to the other parts of code.

Please provide me access to contribute so that i will create a branch upload my changes for review.

**Comment by ccordoba12** [comment]
You can fork this repo, create a branch on it to do your changes and then submit a pull request from it.

We don't work with branches created directly on this repo, so you don't need extra permissions for that.

**Comment by npradeep357** [comment]
> You can fork this repo, create a branch on it to do your changes and then submit a pull request from it.
> 
> We don't work with branches created directly on this repo, so you don't need extra permissions for that.

Sure will do that

**Comment by krassowski** [comment]
@npradeep357 not sure how helpful this is but [jupyter_lsp](https://github.com/jupyter-lsp/jupyterlab-lsp/tree/master/python_packages/jupyter_lsp) is basically WebSockets proxy and it does not require any modifications to the pylsp itself.

**Comment by npradeep357** [comment]
@krassowski it seems helpful… will this support multiple web socket connections (each connection will be a separate IDE session)? Also, it seems this is directly written for jupyter lab (the name also suggests so). Does this work with a different editor (let’s say some web editor like code-mirror which I’m trying to connect to using code-mirror lsp client)?

I did not find any documentation on how to deploy it. Can you point me..

Thank you for the reference

**Comment by npradeep357** [comment]
Hi @ccordoba12, created pull request with necessary code changes. Please review and let me know if any changes required.

here: #128 
thank you
