### ISSUE TITLE
Is it possible to select Python interpreter?

### ISSUE THREAD

**Issue by pplonski** [python-lsp/python-lsp-server#120]
Can I have one instance of pylsp and several virtual envs and just select the env that I would like to work with? Is there any configuration for this?

Or do I need to install pylsp on each venv?

**Comment by ccordoba12** [comment]
>  Is there any configuration for this?

Yes, there is. All our configurations options are documented here:

https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md

The one you're looking for is `pylsp.plugins.jedi.environment`. You need to set your Python environment executable (i.e. `/path/to/myenv/python`) on it.
