### ISSUE TITLE
Warning about installation folder not being on PATH (even though it is)

### ISSUE THREAD

**Issue by kaddkaka** [python-lsp/python-lsp-server#131]
I just installed pylsp on a relatively fresh computer running Xubuntu (Ubuntu 21.10 `impish` and xfce 4.16), python 3.9.7 and pip3 20.3.4

After installing pylsp in my shell fish (version 3.3.1) with this cmd: ` pip3 install python-lsp-server` I saw this warning

```  WARNING: The script pylsp is installed in '/home/david/.local/bin' which is not on PATH.```

even though this folder is on my path.

**Comment by ccordoba12** [comment]
Hey @kaddkaka, thanks for reporting. That warning is not printed by us and I don't know how to avoid it, sorry.
