### ISSUE TITLE
PEP 582 support?

### ISSUE THREAD

**Issue by Gradecak** [python-lsp/python-lsp-server#132]
Hi all, 

Just curious if there are any plans to support the loading of project local packages from `__pypackages__` directory, as per  [PEP 582](https://www.python.org/dev/peps/pep-0582/) 

Or even better, if this is somehow supported would it be possible to point me in the right direction to get `pylsp` to pick it up?

Thanks!

**Comment by krassowski** [comment]
As this is not an approved PEP, I would say that no one is working actively to support it (the details might change, or the PEP may be rejected). However, some of tools used by `pylsp` already support PEP 582 (like jedi: https://github.com/davidhalter/jedi/issues/839). I think to make it work you could start by auditing what other dependencies do support it or don't (and whether some declared that they won't unless the PEP is accepted) and then document what changes are needed to pylsp.

**Comment by vikigenius** [comment]
If you are using emacs here is how you can do it for lsp-python-ms https://github.com/pdm-project/pdm/discussions/372#discussion-3303501.

A similar thing should be possible with python-lsp-server as long as there is an option to add extra search paths.

**Comment by Gradecak** [comment]
Thank you both for the helpful responses! 

The  `pdm` + `lsp-python-ms` setup is what prompted me to attempt to replicate the setup with `pylsp`.  Unfortunately, as @krassowski has pointed out above its not quite as straight forward as I originally had thought, as all tools used by the python language server must also have this capability. In my particular case I put looking into this on pause once I discovered that `mypy` does not yet support searching for library stubs in  `__pypackages__`.

Hopefully something as simple as extra search paths would be possible in the future, if the PEP is approved and gains larger adoption.

**Comment by vikigenius** [comment]
That's weird, how does mypy detect venvs? It should be getting that path somewhere right? Why not just modify that mechanism to point to wherever the libs are stored inside __pypackages__ ?

**Comment by Gradecak** [comment]
If I'm not mistaken when you activate a virtualenv your `PYTHONPATH` changes and now points to the virtualenv and all the packages contained within. I don't believe that mypy has the ability to detect a virtualenv or knows that it is running inside of a virtualenv.

The same is likely (almost certainly) possible with `__pypackages__` , however I would like to accomplish this natively within the tool without needing to activate (or even create) a virtualenv for each project I switch to. This requires the tool in question to search for `__pypackages__`  in the project root in accordance with PEP582

**Comment by vikigenius** [comment]
@Gradecak true, I know that the ideal situation is to have the tools themselves do it. But that won't happen until the PEP actually makes it. I really like the proposal, but it's been in limbo for a while and it will probably be a while if at all for it to be adopted.

**Comment by nyngwang** [comment]
interested in this one. (It's OK to not support it though)

**Comment by doolio** [comment]
Considering [this PEP is now rejected ](https://peps.python.org/pep-0582/) I think this issue could be closed. If the PEP reappears in some new form then the question of whether `pylsp` provides support can be revisited.

**Comment by ccordoba12** [comment]
Closing then.
