### ISSUE TITLE
Add `DiagnosticTag` tags for pylint, pycodestyle, and flake8

### ISSUE THREAD

**Issue by krassowski** [python-lsp/python-lsp-server#144]
As a follow up to #142 we can now add `tags` to diagnostics for specific plugins.
This would likely need to be based on matching the error codes.

- pylint (https://pylint.pycqa.org/en/v2.12.2/technical_reference/features.html):
  - Deprecated:
     - W0402: Uses of a deprecated module %r
      - W1505: Using deprecated method %s()
     - W1511: Using deprecated argument %s of method %s()
     - W1512: Using deprecated class %s of module %s
     - W1513: Using deprecated decorator %s()
  - Unnecessary:
     - W0611: Unused import %s
     - W0612: Unused variable %r
     - W0613: Unused argument %r
     - W0614: Unused import %s from wildcard import
     - W1304: unused-format-string-argument
- pycodestyle (https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes):
   - Deprecated: all codes starting with W6
- flake8 (https://flake8.pycqa.org/en/latest/user/error-codes.html):
   - Unnecessary:
     - F401: module imported but unused
     - F504: % format unused named arguments
     - F522: .format(...) unused named arguments
     - F523: .format(...) unused positional arguments

I think it's worth the effort, but wanted to first see if you agree. Happy to make a PR with the changes.

**Comment by ccordoba12** [comment]
Could you post an example of a reply that includes the tag?

**Comment by krassowski** [comment]
```javascript
/**
 * @deprecated
 */
function oldFunc(test) { 
    return;
    let x = 1;
}
oldFunc
```

```json
{
    "uri": "javascript_test.js",
    "diagnostics": [
        {
            "range": {
                "start": {
                    "line": 3,
                    "character": 17
                },
                "end": {
                    "line": 3,
                    "character": 21
                }
            },
            "message": "'test' is declared but its value is never read.",
            "severity": 4,
            "code": 6133,
            "source": "typescript",
            "tags": [
                1
            ]
        },
        {
            "range": {
                "start": {
                    "line": 5,
                    "character": 4
                },
                "end": {
                    "line": 5,
                    "character": 14
                }
            },
            "message": "Unreachable code detected.",
            "severity": 4,
            "code": 7027,
            "source": "typescript",
            "tags": [
                1
            ]
        },
        {
            "range": {
                "start": {
                    "line": 5,
                    "character": 8
                },
                "end": {
                    "line": 5,
                    "character": 9
                }
            },
            "message": "'x' is declared but its value is never read.",
            "severity": 4,
            "code": 6133,
            "source": "typescript",
            "tags": [
                1
            ]
        },
        {
            "range": {
                "start": {
                    "line": 7,
                    "character": 0
                },
                "end": {
                    "line": 7,
                    "character": 7
                }
            },
            "message": "'oldFunc' is deprecated",
            "severity": 4,
            "code": 6385,
            "source": "typescript",
            "tags": [
                2
            ]
        }
    ]
}
```

I'm rendering it as:

![Screenshot from 2021-12-31 01-28-09](https://user-images.githubusercontent.com/5832902/147797745-8f6e4f8b-f3f3-4bcf-8282-df96921e2bc6.png)

because:

```
export namespace DiagnosticTag {
	/**
	 * Unused or unnecessary code.
	 *
	 * Clients are allowed to render diagnostics with this tag faded out
	 * instead of having an error squiggle.
	 */
	export const Unnecessary: 1 = 1;
	/**
	 * Deprecated or obsolete code.
	 *
	 * Clients are allowed to rendered diagnostics with this tag strike through.
	 */
	export const Deprecated: 2 = 2;
}
```

**Comment by ccordoba12** [comment]
Ok, I see. Then it's just extra metadata in the request. Then I'm fine with your proposal.
