### ISSUE TITLE
Is there any way to have the "pycodestyle" message toggle? (Neovim) (cmp)

### ISSUE THREAD

**Issue by CleoMenezesJr** [python-lsp/python-lsp-server#145]
I found a way to remove it with the configuration below. But the intention is not to remove it, but just to be able to switch between hidden or not, and that the yellow line that indicates where the problem is remains there:

![image](https://user-images.githubusercontent.com/54215258/147861914-296bbc20-fc44-4d68-bf17-3a318a79572d.png)

**Comment by ccordoba12** [comment]
The pycodestyle plugin can be enabled/disabled (as any other plugin), as described in our configuration file:

https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md

For that, clients (in this case Neovim) need to send a `workspace/didChangeConfiguration` request to that effect. So it's not something we can solve here. We only provide the option to do that, but clients need to decide what to do with it.

Sorry to not be more specific, but that really depends on each client.
