### ISSUE TITLE
README.md: Windows users trying to install the *extras* in `cmd.exe` need to use double quotes instead of single quotes

### ISSUE THREAD

**Issue by ScientificProgrammer** [python-lsp/python-lsp-server#150]
Hi,

I'm posting this comment in case it's useful to others who are running Python on MS Windows.
I'm running Windows 11. I've configured my system so as to be to call `python` or `python3`
from `cmd.exe` the same way as is done on Linux systems, as opposed to the Windows specific
manner, which is to call the *Windows Python Launcher*, `py.exe`, that is located at `C:\\Windows\\py.exe`.

I was trying to install the *extras* packages for `python-lsp-server`. In the [README.md](https://github.com/python-lsp/python-lsp-server/blob/7b98f9f6ccc2338552a325d9f06a4d71198e1dae/README.md) file for this repo,
the installation instructions for installing all of the *extras* shows the following command:

    pip install 'python-lsp-server[all]'

However, that command didn't work for me until I changed the single-quote characters to double quote characters, as shown below.

    D:\tmp_SublimeText4>python3 -m pip install 'python-lsp-server[all]'
    ERROR: Invalid requirement: "'python-lsp-server[all]'"

    D:\tmp_SublimeText4>python3 -m pip install "python-lsp-server[all]"
    Requirement already satisfied: python-lsp-server[all] in d:\program files\python310\lib\site-packages (1.3.3)
    Requirement already satisfied: python-lsp-jsonrpc>=1.0.0 in d:\program files\python310\lib\site-packages (from python-lsp-server[all]) (1.0.0)
    Requirement already satisfied: setuptools>=39.0.0 in d:\program files\python310\lib\site-packages (from python-lsp-server[all]) (60.3.1)
    Requirement already satisfied: pluggy in d:\program files\python310\lib\site-packages (from python-lsp-server[all]) (1.0.0)
    Requirement already satisfied: jedi<0.19.0,>=0.17.2 in d:\program files\python310\lib\site-packages (from python-lsp-server[all]) (0.18.1)
    Requirement already satisfied: ujson>=3.0.0 in d:\program files\python310\lib\site-packages (from python-lsp-server[all]) (5.1.0)
    Collecting yapf
      Using cached yapf-0.32.0-py2.py3-none-any.whl (190 kB)
    Requirement already satisfied: pyflakes<2.5.0,>=2.4.0 in d:\program files\python310\lib\site-packages (from python-lsp-server[all]) (2.4.0)
    Requirement already satisfied: flake8<4.1.0,>=4.0.0 in d:\program files\python310\lib\site-packages (from python-lsp-server[all]) (4.0.1)
    Requirement already satisfied: pylint>=2.5.0 in d:\program files\python310\lib\site-packages (from python-lsp-server[all]) (2.12.2)
    Requirement already satisfied: pycodestyle<2.9.0,>=2.8.0 in d:\program files\python310\lib\site-packages (from python-lsp-server[all]) (2.8.0)
    Collecting rope>=0.10.5
      Using cached rope-0.22.0-py3-none-any.whl (185 kB)
    Collecting autopep8<1.7.0,>=1.6.0
      Using cached autopep8-1.6.0-py2.py3-none-any.whl (45 kB)
    Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in d:\program files\python310\lib\site-packages (from python-lsp-server[all]) (0.6.1)
    Requirement already satisfied: pydocstyle>=2.0.0 in d:\program files\python310\lib\site-packages (from python-lsp-server[all]) (6.1.1)
    Requirement already satisfied: toml in d:\program files\python310\lib\site-packages (from autopep8<1.7.0,>=1.6.0->python-lsp-server[all]) (0.10.2)
    Requirement already satisfied: parso<0.9.0,>=0.8.0 in d:\program files\python310\lib\site-packages (from jedi<0.19.0,>=0.17.2->python-lsp-server[all]) (0.8.3)
    Requirement already satisfied: snowballstemmer in d:\program files\python310\lib\site-packages (from pydocstyle>=2.0.0->python-lsp-server[all]) (2.2.0)
    Requirement already satisfied: platformdirs>=2.2.0 in d:\program files\python310\lib\site-packages (from pylint>=2.5.0->python-lsp-server[all]) (2.4.1)
    Requirement already satisfied: colorama in d:\program files\python310\lib\site-packages (from pylint>=2.5.0->python-lsp-server[all]) (0.4.4)
    Requirement already satisfied: isort<6,>=4.2.5 in d:\program files\python310\lib\site-packages (from pylint>=2.5.0->python-lsp-server[all]) (5.10.1)
    Requirement already satisfied: astroid<2.10,>=2.9.0 in d:\program files\python310\lib\site-packages (from pylint>=2.5.0->python-lsp-server[all]) (2.9.2)
    Requirement already satisfied: wrapt<1.14,>=1.11 in d:\program files\python310\lib\site-packages (from astroid<2.10,>=2.9.0->pylint>=2.5.0->python-lsp-server[all]) (1.13.3)
    Requirement already satisfied: lazy-object-proxy>=1.4.0 in d:\program files\python310\lib\site-packages (from astroid<2.10,>=2.9.0->pylint>=2.5.0->python-lsp-server[all]) (1.7.1)
    Installing collected packages: yapf, rope, autopep8
    Successfully installed autopep8-1.6.0 rope-0.22.0 yapf-0.32.0

    D:\tmp_SublimeText4>

I hope this information is helpful to you and others.

**Comment by ccordoba12** [comment]
Hey @ScientificProgrammer, thanks for reporting. Please submit a pull request to fix that.

**Comment by ScientificProgrammer** [comment]
I just forked the repo, but when I looked for repo-specific instructions on how to submit a PR, I didn't see any. I noticed there are quite a few branches, and they look to be named somewhat systematically. Unless you tell me otherwise, my plan is to do the following.

1. Create a new branch that, to the best of my ability, conforms to the existing naming scheme. Here's what I'm thinking: `fix-readme-squo-to-dquo`

2. Make changes on that branch.

3. Submit the PR and let your team merge into `develop` (or whichever branch you prefer).

Can you please let me know if this plan sounds good to you?

**Comment by ccordoba12** [comment]
Yes, it does. Please derive your branch from `develop` too. That's the main branch on this repo.

**Comment by ScientificProgrammer** [comment]
OK, I made the changes and created PR #163 . Please let me know if you want me to close this issue here, or if your team would prefer to take that action after reviewing the PR. Please note that I also included a link to this issue from the PR.

**Comment by ccordoba12** [comment]
Thanks for your help @ScientificProgrammer! This issue will be closed automatically once I merge your pull request.
