### ISSUE TITLE
Settings not taken into account, with no errors

### ISSUE THREAD

**Issue by augustebaum** [python-lsp/python-lsp-server#152]
Hi all,

I'm using `pylsp` version 1.3.3 with the `nvim` builtin LSP client:
```
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey
```

My simplified config is the following:
```lua
local lspconfig = require "lspconfig"

local servers = {
  pylsp = {
    configurationSources = {"pylint"},
    plugins = {
      pylint = { enabled = true },
      flake8 = { enabled = false },
      pycodestyle = { enabled = false },
      pyflakes = { enabled = false },
    }
  },
}

local client_capabilities = vim.lsp.protocol.make_client_capabilities()
client_capabilities.textDocument.completion.completionItem.snippetSupport = true
client_capabilities.textDocument.completion.completionItem.resolveSupport = {
  properties = { 'documentation', 'detail', 'additionalTextEdits' },
}
-- for nvim_cmp
client_capabilities = require('cmp_nvim_lsp').update_capabilities(client_capabilities)

for server, config in pairs(servers) do
  if type(config) == 'function' then
    config = config()
  end
  config.on_attach = on_attach
  config.capabilities = vim.tbl_deep_extend(
    'keep',
    config.capabilities or {},
    client_capabilities
  )
  lspconfig[server].setup(config)
end
```

I only want `pylint` to be active; I've explicitely deactivated `pyflakes` and `pycodestyle` since apparently they are on by default.
I've also set my `configurationSources` to just `pylint` for the same reason.

However, when I open a Python file, I can see linting diagnostics from `pyflakes` and `pycodestyle` (basically only "line too long" errors -- not the most useful stuff).

It seems like my config is not being taken into account. Would anyone know how to investigate this further?

PS: Would you know how to configure `pycodestyle` so that it doesn't track line lengths?

Thanks for reading; looking forward to using `pylsp` at its full capacity!

**Comment by ccordoba12** [comment]
Hey @augustebaum, thanks for reporting. Please report this problem in Neovim (or `nvim_cmp`, not really sure) because it seems to be a problem on its side, not here.

We do exactly the same as you're trying to do in Spyder (i.e. enabling some plugins and disabling others) and that works flawlessly. So your bug is not present here.

**Comment by ccordoba12** [comment]
> PS: Would you know how to configure pycodestyle so that it doesn't track line lengths?

See our Configuration file for all available options:

https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md

**Comment by mjlbach** [comment]
That example is wrong, you need to pass an explicit `settings` table in the `config` object.

**Comment by augustebaum** [comment]
Thanks for the quick feedback!

Changed the `pylsp` part of the config to:
```lua
local servers = {
  pylsp = {
    cmd = {"pylsp"},
    root_dir = function(fname)
      local root_files = {
        'pyproject.toml',
        'setup.py',
        'setup.cfg',
        'requirements.txt',
        'Pipfile',
      }
      return util.root_pattern(unpack(root_files))(fname) or util.find_git_ancestor(fname)
    end,
    settings = {
      configurationSources = {"pylint"},
      plugins = {
        pylint = { enabled = true },
        flake8 = { enabled = false },
        pycodestyle = { enabled = false },
        pyflakes = { enabled = false },
      }
    }
  }
}
```
to no avail. Was this the change you had in mind?

I also tried turning `pycodestyle` back on with the `maxLineLength` set to 100, also without success.

**Comment by mjlbach** [comment]
I don't use pylsp, at a glance it should be:
```
   settings = {
      pylsp = { 
        configurationSources = {"pylint"},
        plugins = {
          pylint = { enabled = true },
          flake8 = { enabled = false },
          pycodestyle = { enabled = false },
          pyflakes = { enabled = false },
        }
    }
```
You can ask on the neovim discourse if you have issues.

**Comment by omertuc** [comment]
Thanks @mjlbach - that worked for me 

For anyone else looking, this is an example of a full `servers` var definition that seems to work for me based on @mjlbach's comment, quite a bit of nesting:

```lua
local servers = {
        ... <other_servers_omitted>
        
	pylsp = {
		settings = {
			pylsp = {
				plugins = {
					pylint = { enabled = true },
					flake8 = { enabled = false },
					pycodestyle = { enabled = false },
					pyflakes = { enabled = false },
				},
			},
		},
	},
	
	... <other_servers_omitted>
}
```
