### ISSUE TITLE
3d Party Plugins couldn't be configured

### ISSUE THREAD

**Issue by Ae-Mc** [python-lsp/python-lsp-server#155]
How to pass mypy/black/etc. configuration in didChangeConfiguration method of python-lsp-server?

**Comment by krassowski** [comment]
By passing a JSON object, keyed as described in https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md

**Comment by Ae-Mc** [comment]
There is no mypy configuration, is there?

**Comment by ccordoba12** [comment]
That depends on each plugin, so it doesn't need to be reported here.

* For python-lsp-black, there are [plans](https://github.com/python-lsp/python-lsp-black/pull/26) to support options in a future version (most probably 1.2.0) to be released in a couple of months
* For pylsp-mypy, please open an issue on its repo about it: https://github.com/python-lsp/pylsp-mypy

**Comment by Ae-Mc** [comment]
Thank you

**Comment by haplo** [comment]
> How to pass mypy/black/etc. configuration in didChangeConfiguration method of python-lsp-server?

What kind of configuration are you looking for the black plugin? Besides enabling configuration caching my only idea right now is a way of explicitly enabling/disabling the plugin, but I would like to hear other to ideas.

**Comment by Ae-Mc** [comment]
Line length and --preview flag at least

**Comment by haplo** [comment]
> Line length and --preview flag at least

I think that is out of scope for the plugin and you would be better off using a black configuration file for it. [_python-lsp-black_ will now use black's global configuration file](https://github.com/python-lsp/python-lsp-black/issues/25), so you could have one with your preferred line length, and override per-project if necessary.

What is `--preview`?

**Comment by ccordoba12** [comment]
I agree with line length. We need that for Spyder too, so I'll take care of it in `python-lsp-black`.

**Comment by Ae-Mc** [comment]
@haplo, please check black docs:
```
--preview                       Enable potentially disruptive style changes
                                that will be added to Black's main
                                functionality in the next major release.
```

**Comment by haplo** [comment]
> @haplo, please check black docs:
> 
> ```
> --preview                       Enable potentially disruptive style changes
>                                 that will be added to Black's main
>                                 functionality in the next major release.
> ```

Thank you @Ae-Mc, I ran `black --help` but didn't see it there.

**Comment by Ae-Mc** [comment]
It was introduced in Black 22.1.0:
![image](https://user-images.githubusercontent.com/43097289/158998727-64139144-3cd9-4859-9de1-f24ba1aacdc8.png)

**Comment by ccordoba12** [comment]
@Ae-Mc, I added support for that option in https://github.com/python-lsp/python-lsp-black/pull/26.
