### ISSUE TITLE
Please add basic usage documentation

### ISSUE THREAD

**Issue by pkars** [python-lsp/python-lsp-server#157]
Hello,
the README seems to be lacking in the actual usage information. Could you kindly add a short section to the README describing the basic usage?

For example, there are no instructions on i) how to start and stop the server (manually), ii) what command I should provide to the client software (e.g. to Kate's [LSP plugin](https://docs.kde.org/stable5/en/kate/kate//kate-application-plugin-lspclient.html)), or iii) how to check if the LSP server was installed successfully. 

In my opinion, having simple "_check that the installation is found by running `pylsp --version`_" -esque instructions in the README would be great, and probably enough for the users who are not planning to write their own LSP client software/plugins.

Thanks.

**Comment by ccordoba12** [comment]
You're welcome to improve our Readme to inform users about this, but the info you requested is in `pylsp --help`.

**Comment by ccordoba12** [comment]
> ii) what command I should provide to the client software (e.g. to Kate's LSP plugin)

There's a Python entry on that page. Just change `pyls` for `pylsp`.

**Comment by zeta-00** [comment]
I'm having trouble getting python-lsp-server working with Eglot. If you could document how to do that, then that would be great.

**Comment by ccordoba12** [comment]
The command to start the server is

    python3 -m pylsp --check-parent-process

Where to put that command and how to connect to the server depends on your client (Eglot, Kate, Neovim, etc). This project is only about the PyLSP server, that's why we can't add more documentation about it.

**Comment by zeta-00** [comment]
Ok thanks, I'll go ask the Emacs Eglot devs.
