### ISSUE TITLE
[question] setting custom pythonpath in a per project settings file

### ISSUE THREAD

**Issue by rafaelleru** [python-lsp/python-lsp-server#162]
Hi all, sorry for asking here but I could not find the solution on jedi documentation neither on SO or pylsp docs.

Is there a way to custom set my pythonpath only for certain projects? I can do it via venv but I don't know how to do it with a config file in order to use it with the global LSP server in my machine.

Thanks.

**Comment by npradeep357** [comment]
@rafaelleru, What to do you mean by certain projects? Do you want to run this pylsp on a custom python (other than the globally installed one)?

**Comment by cbensimon** [comment]
@npradeep357 Is it actually be possible to run pylsp on a custom python ?
Thanks.

**Comment by ccordoba12** [comment]
Moving this to our new Discussions forum so you can keep talking about it there.
