### ISSUE TITLE
an easy question

### ISSUE THREAD

**Issue by XXiaoA** [python-lsp/python-lsp-server#164]
i want the pylsp.plugins.flake8.maxLineLength = 120
however, i don't know how to change it. who can help me? i have tried all the method that i can think.

**Comment by XXiaoA** [comment]
In other words, i want to configure my pylsp

**Comment by ccordoba12** [comment]
You need to send a didChageConfiguration request from your editor or IDE. Please ask how to do that in the repo of the one you're using right now.

The options this server supports are in the CONFIGURATION.md file.

**Comment by XXiaoA** [comment]
okay, i'm using noevim in ubuntu. so how should i do to send a didChageConfiguration request? i tried `:let g:pylsp_plugins_flake8_maxLineLength = 120`in normal mode.strangely, it didn't work but didn't throw a error.

**Comment by ccordoba12** [comment]
I don't use Neovim nor the other maintainers of this project. As I said, please ask for help in your editor repo or forums.

**Comment by XXiaoA** [comment]
Thanks for your help
