### ISSUE TITLE
use of `lsp-clients-pylsp-library-directories`

### ISSUE THREAD

**Issue by onekk** [python-lsp/python-lsp-server#167]
Hello.

I have installed a program using conda, "FreeCAD"  so the libraries are not in PYTHONPATH

but when writing code for this program I wish to have the introspection active. in other word if int the Python code I do:

```
import FreeCAD
import Part

test = Part.
```

I whish to be able to use "Go to Definition" right click item menu.

I'm using emacs 27.1

I have found the location of the relevant source code and I have customized the variable   `lsp-clients-pylsp-library-directories` using emacs customization

But I get an error `LSP:: Not found for: FreeCAD` 

How to get things working.

Regards

Carlo D.

**Comment by ccordoba12** [comment]
Hey @onekk, thanks for reporting. We have no idea how that variable works because we don't use Emacs. So, please report this problem with its maintainers instead.

**Comment by onekk** [comment]
Sorry for the inconvenience.

Regards
