### ISSUE TITLE
Could you open GitHub discussion for normal people asking (simple) questions?

### ISSUE THREAD

**Issue by nyngwang** [python-lsp/python-lsp-server#168]
As title.

**Comment by ccordoba12** [comment]
@spookylukey, @carltongibson, thoughts about this?

This could help people from editors/IDEs we don't use to share their configuration issues and files, so they can assist each other.

**Comment by carltongibson** [comment]
I think that it's not easy seeing how to get set up, or customising, so either discussions, or a list of examples, that can grow as they come up would be useful. 

I suspect that a few examples would go a long way, but right now there aren't many. (Still to sit down with the example you pointed at in #171, which looks very helpful!)

**Comment by nyngwang** [comment]
## Here I provide some motivations:

(Forgive me to use the word _competitor_.)

I think pylsp needs a community to win the competitor pyright*. We need a place for people to ask simple questions to grow faster than pyright. (healthy competition, I hope. And I don't think StackOverflow is a better place because these configuring problems, in general, contain too many details, so more suitable to discuss directly among the maintainers/contributors.)

---

*: I'm a very heavy neovim user. I'm probably among the top 1% users who know about how to set it up correctly. Some little proof (statistics 3/14~ by Wakatime):

<img src="https://user-images.githubusercontent.com/24765272/158904832-c3b8d281-51e9-48d5-a98b-e3504214b932.png" width="400">

If the community can be created, I'm willing to provide consistent support in answering neovim-related (simple to intermediate) questions, and further report the possible bugs upstream neovim-related repos when needed. (I believe newbies don't know how to do this _faster_.)

Finally, I read some comments saying that pyright is better (in terms of speed) than pylsp. But recently, I encountered a bug during trying [PDM](https://github.com/pdm-project/pdm) that pyright will creat two `node` processes hanging there eaten-up 99% CPU. 

Anyway, I hope pylsp will benefit from the GitHub discussion feature.

Sincerely,
Ning.

**Comment by nyngwang** [comment]
From my current observation, some issues could be put in GitHub Discussion, https://github.com/python-lsp/python-lsp-server/issues/172 for example. So you can benefit from the distinction between _real_ lsp related __issues__ and _editor configuration_ __discussion__. But beware that while these kinds of questions might be simple/having low-priority, __they're the real users__ of pylsp. We must treat these questions correctly so they will stay.

**Comment by ccordoba12** [comment]
> (Forgive me to use the word competitor.)

I think that's fine, don't worry.

> I think pylsp needs a community to win the competitor pyright*

Well, the problem is that Pyright is sponsored by Microsoft and we're a community effort. The nice thing about us though is that our server is based on Python (so you don't need a separate Node installation to run it), we integrate with a lot of widely used tools in the Python community, and we offer a nice way to configure them.

> If the community can be created, I'm willing to provide consistent support in answering neovim-related

Cool! Thanks a lot for offering your help @nyngwang!

> Finally, I read some comments saying that pyright is better (in terms of speed)

Jedi (the library we use for most operations) is actually quite performant and provides better results in some situations. The thing is client/IDEs need to optimize a lot how they interact with the server to get good results.

> But recently, I encountered a bug during trying [PDM](https://github.com/pdm-project/pdm) that pyright will creat two node processes hanging there eaten-up 99% CPU.

That's not surprising because Pyright is (most probably) optimized to work best with VScode.

> Anyway, I hope pylsp will benefit from the GitHub discussion feature.

I just opened our Discussions, so enjoy!

**Comment by ccordoba12** [comment]
> From my current observation, some issues could be put in GitHub Discussion, https://github.com/python-lsp/python-lsp-server/issues/172 for example

Good point. I'll move it there.

> But beware that while these kinds of questions might be simple/having low-priority, they're the real users of pylsp. We must treat these questions correctly so they will stay.

Good point. The thing is we need others' help for that because we don't have experience with most editors/IDEs our users come here for.

**Comment by doolio** [comment]
I think this issue can be closed.

**Comment by ccordoba12** [comment]
Correct.
