### ISSUE TITLE
cannot disable pyflakes and enable flake8 / jlab console full of LSP.WidgetAdapter warnings

### ISSUE THREAD

**Issue by michaelaye** [python-lsp/python-lsp-server#169]
Using 
* JLab 3.3.0
* pylsp 1.2.1

![image](https://user-images.githubusercontent.com/69774/157319214-7d9b50d1-119e-4f0c-af0b-77fdbbc6b369.png)

I'm trying to disable pyflakes and enable flake8 but am unable to do so with the following settings in jlab:

```json
{
    pylsp: {
        serverSettings: {
            "pylsp.plugins.pyflakes.enabled": false,
            "pylsp.plugins.flake8.enabled": true,
        }
    }
}
```

**Comment by ccordoba12** [comment]
Please report this in JupyterLab-LSP. We can't solve it here.

**Comment by ccordoba12** [comment]
To be clearer, we don't know how to solve this problem because it depends on the way JupyterLab-LSP works. So this is not the right place to ask for help.
