### ISSUE TITLE
Python missing from LSP servers when using jupyterlab-lsp

### ISSUE THREAD

**Issue by maresb** [python-lsp/python-lsp-server#17]
Hi, I'm very excited to see development moving forward here!

I'm trying to get this running in my Dockerized development environment. I used `mamba` to install `python-lsp-jsonrpc 1.0.0`, `python-lsp-server 1.0.1`, and `jupyterlab-lsp 3.5.0` from conda-forge. I can successfully run `pylsp` from the command line. However, it does not seem to be recognized by `jupyterlab-lsp`.

In contrast, palantir/python-language-server is recognized automatically by jupyterlab-lsp. Is some additional configuration expected/necessary? Thanks!

![image](https://user-images.githubusercontent.com/15216687/115971339-29a77200-a548-11eb-9d16-a3bbae0266cb.png)

**Comment by krassowski** [comment]
jupyterlab-lsp does not autodetect pylsp yet. We basically need to copy-paste https://github.com/krassowski/jupyterlab-lsp/blob/master/python_packages/jupyter_lsp/jupyter_lsp/specs/pyls.py as python_lsp_server.py and change pyls references to python-lsp-server. Feel free to open a PR.

**Comment by ccordoba12** [comment]
Closing because this is an issue with `jupyterlab-lsp`
