### ISSUE TITLE
Support for pylint?

### ISSUE THREAD

**Issue by stefaneidelloth** [python-lsp/python-lsp-server#171]
If I run pylint with nbqa against my notebook, I get a warning

`W0622: Redefining built-in 'map' (redefined-builtin)`

In the notebook I do get a warning about trailing white space but I
don't get a warning about the build-in name from lsp. 

Therefore, I was wondering if lsp supports pylint checks or some alternative
tool that would give me that warning?

![image](https://user-images.githubusercontent.com/12675339/158156446-27e67ee2-1f9b-4e6d-a6b9-8410912d77f4.png)

**Comment by edubxb** [comment]
Hi!

Pylint is supported, but disabled by default.

https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md

**Comment by stefaneidelloth** [comment]
Here is the JupyterLab config for the LanguageServer tab that worked for me to enable pylint:

```
{  
    "language_servers": {
        "pyright": {
            "serverSettings": {
                "python.analysis.useLibraryCodeForTypes": true
            }
        },
        "pylsp": {
            "serverSettings": {
                "pylsp": {
                    "plugins": {
                        "pydocstyle": {
                          "enabled": true
                        },
                        "pyflakes": {
                          "enabled": false
                        },
                        "flake8": {
                          "enabled": true
                        },
                        "pylint": {
                          "enabled": true
                        }
                    }
                }
            }
        }
    }
    
}
```
