### ISSUE TITLE
Enabling completions from Conda virtual envs

### ISSUE THREAD

**Issue by skeledrew** [python-lsp/python-lsp-server#178]
Hello. I use Conda to manage my virtual envs and [autoenv](https://github.com/hyperupcall/autoenv) to activate them per project. I would like to get completions from the packages in the envs for these projects. How can I go about specifying the additional search path to the jedi plugin (I don't mind patching the server code itself if that gets me there quickly)? I'd rather do this on the server side as I use Emacs with [lsp-mode](https://github.com/emacs-lsp/lsp-mode/), and I'm not very good with ELisp. Thank you.

**Comment by ccordoba12** [comment]
Hey @skeledrew, thanks for reporting. Please post your question in this discussion:

https://github.com/python-lsp/python-lsp-server/discussions/177

Also, from now on please use our Discussions forum to ask for support. Issues are only meant to report errors.
