### ISSUE TITLE
Configuration is ignored

### ISSUE THREAD

**Issue by glottis9** [python-lsp/python-lsp-server#183]
I can't get pylsp to honor my config.  I put [flake8] and/or [pycodestyle] sections in setup.cfg but still get errors in my buffer.  I also have the following elisp:

(setq lsp-pylsp-configuration-sources ["flake8"]
lsp-pylsp-plugins-flake8-ignore ["D100" "D103" "E501"])

and that doesn't work either.  Any idea what I need to do?

**Comment by ccordoba12** [comment]
Hey @glottis9, thanks for reporting. Please use our [Discussions](https://github.com/python-lsp/python-lsp-server/discussions) to ask for support. Issues are only meant to report errors in the server.

**Comment by ccordoba12** [comment]
Hey @glottis9, thanks for reporting. Please use our [Discussions](https://github.com/python-lsp/python-lsp-server/discussions) to ask for support. Issues are only meant to report errors in the server.
