### ISSUE TITLE
Documentation for Minimal Configuration

### ISSUE THREAD

**Issue by ghost** [python-lsp/python-lsp-server#188]
Please add a section in README for a minimal emacs configuration that works with `python-lsp-server`.

I have done the following:

+ Install Python Language Server Protocol for my user

  ```
  pip3 install --user 'python-lsp-server[all]'
  pip3 install --user 'python-language-server[all]'
  ```

+ Add directory to `PATH`, as suggested by Homebrew

+ And in Emacs:

  1. Add Melpa repository to `init.el`

    ```
    (require 'package)
    (add-to-list 'package-archives
                 '("melpa" . "http://melpa.org/packages/") t)
    (package-initialize)
    (package-refresh-contents)
    ``` 

  2. Installed Emacs packages:

    a) use-package
    b) lsp-mode
    c) dap-mode

  3. At the bottom add:

    ```
    (use-package python-mode
      :ensure t
      :hook (python-mode . lsp-deferred)
      :custom
      ;; NOTE: Python 3 is called "python3"
      (python-shell-interpreter "python3")
      (dap-python-executable "python3")
      (dap-python-debugger 'debugpy)
      :config
      (require 'dap-python))
    ```

But this throws an error:

```
LSP :: The following servers support current file but do not have automatic installation: pyls pylsp
You may find the installation instructions at https://emacs-lsp.github.io/lsp-mode/page/languages.
(If you have already installed the server check *lsp-log*).
```

**Comment by ccordoba12** [comment]
Hey @saurabh-mish, thanks for reporting. Please post your message in our new [Discussions](https://github.com/python-lsp/python-lsp-server/discussions) forum so other Emacs users can give you a hand with your problem. That's because issues are only to report errors and none of maintainers use Emacs.
