### ISSUE TITLE
Linter and tests are failing on due to new "consider-using-with"

### ISSUE THREAD

**Issue by krassowski** [python-lsp/python-lsp-server#19]
Yesterday's release of Pylint 2.8 added `consider-using-with` among other [new checkers](https://github.com/PyCQA/pylint/blob/af1ac5ebe1c845b7eb736863826d75e3994c496c/doc/whatsnew/2.8.rst#new-checkers). The tests are currently failing on master in six places and I will try to fix them by refactoring to use the `with` statement if possible, or adding `# pylint: disable=consider-using-with` otherwise.

**Comment by ccordoba12** [comment]
Thanks for giving us a hand with that @krassowski!
