### ISSUE TITLE
Child processes spawned by the LSP server become zombies

### ISSUE THREAD

**Issue by prvnsmpth** [python-lsp/python-lsp-server#196]
I'm running into an issue with the LSP server leaving behind child process and was wondering if someone could help me understand what I'm doing wrong. 

I am able to run the LSP and interact with it correctly - everything works as expected. I can see that the main process spawns a child process:
```
/app # ps -e -o pid,ppid,pgid,stat,user,comm,args 
PID   PPID  PGID  STAT USER     COMMAND          COMMAND
    1     0     1 S    root     npm run dev      npm run dev
  109    19     1 S    root     python3          python3 -m pylsp -v --log-file /var/log/pylsp/current
  124   109     1 S    root     python3          /usr/bin/python3 /usr/lib/python3.8/site-packages/jedi/inference/compiled/subprocess/__main__.py /usr/lib/python3.8/site-packages 3.8.10
```

The LSP process is the one with PID 109, and we can see that it has spawned a child process with PID 124. 

Now, the issue is that when I attempt to kill the LSP, the child process is left behind as a zombie:

```
/app # ps -e -o pid,ppid,pgid,stat,user,comm,args 
PID   PPID  PGID  STAT USER     COMMAND          COMMAND
    1     0     1 S    root     npm run dev      npm run dev
  124     1     1 Z    root     python3          [python3]
  137    38   137 R    root     ps               ps -e -o pid,ppid,pgid,stat,user,comm,args
```
(PID 124 is a zombie process)

I found that attempting to kill the child process with SIGTERM makes it a zombie instead of killing it. This leads me to believe that the parent process is not calling a wait() on the child process. Am I correct in my assessment? 

It would be great if you could point me to the part of the code where this child process is spawned, I can read through it to understand if I'm doing something incorrectly, or if there's something missing in the code.

**Comment by ccordoba12** [comment]
Hey @prvnsmpth, thanks for reporting. Please start `pylsp` with the `--check-parent-process` option and try again.

**Comment by prvnsmpth** [comment]
@ccordoba12 Thank you for your reply! I was away last week and so couldn't try the fix you suggested.

I tried it today and unfortunately it didn't seem to make a difference:

```
/app # ps -e -o pid,ppid,pgid,stat,user,comm,args 
PID   PPID  PGID  STAT USER     COMMAND          COMMAND
    1     0     1 S    root     npm run dev      npm run dev
   19     1     1 S    root     node             node --trace-warnings dist/server/server.js
  104    19     1 S    root     python3          python3 -m pylsp -v --log-file /var/log/pylsp/current --check-parent-process
  113   104     1 S    root     python3          /usr/bin/python3 /usr/lib/python3.8/site-packages/jedi/inference/compiled/subprocess/__main__.py /usr/lib/python3.8/site-packages 3.8.10
  130    97   130 R    root     ps               ps -e -o pid,ppid,pgid,stat,user,comm,args
```

PID 113 above was spawned by PID 104 (which as we can see, was started with `--check-parent-process`).

Upon attempting to kill the entire process tree rooted at PID 104, this is what we end up with:

```
/app # ps -e -o pid,ppid,pgid,stat,user,comm,args 
PID   PPID  PGID  STAT USER     COMMAND          COMMAND
    1     0     1 S    root     npm run dev      npm run dev
   19     1     1 S    root     node             node --trace-warnings dist/server/server.js
  113     1     1 Z    root     python3          [python3]
  137    97   137 R    root     ps               ps -e -o pid,ppid,pgid,stat,user,comm,args
```

PID 104 is gone, but PID 113 is left behind as a zombie. For killing these processes, SIGTERM was sent to both parent and child processes (first to the child, and then the parent). Any other suggestions I can look into?

**Comment by ccordoba12** [comment]
You shouldn't need to send SIGTERM to process 104. Instead, you simply need to close the app that started pylsp in the background with `--check-parent-process` flag. Then pylsp will auto-close itself automatically and 113 should be closed too (that's how we handle things in Spyder).

>  Any other suggestions I can look into?

Nop, I don't have more suggestions. sorry.

**Comment by prvnsmpth** [comment]
If I understand correctly, you are saying that I should kill process 19 in the above example, right?
```
19     1     1 S    root     node             node --trace-warnings dist/server/server.js
```

But doesn't that seem excessive? I have a server process that starts and stops `pylsp` depending on whether a client is connected or idle. If I understand your suggestion correctly, I would need to shutdown and restart this server process, correct? That would mean that all other clients connected to this server get disconnected if just one client goes idle.

Could you please point me to the code where this child process spawning is done in pylsp? I can do some digging to find out what is actually happening.

**Comment by ccordoba12** [comment]
> If I understand correctly, you are saying that I should kill process 19 in the above example, right?

I didn't know what you were doing, but I agree that that's excessive. I just explained you how `--check-parent-process` works.

> Could you please point me to the code where this child process spawning is done in pylsp?

That's done automatically by Jedi. We don't have any control over it.

**Comment by prvnsmpth** [comment]
@ccordoba12 Thank you, I think I will look into Jedi in order to find a fix for this. I suppose we can close this issue.

**Comment by ccordoba12** [comment]
Ok, closing then.
