### ISSUE TITLE
Progress support

### ISSUE THREAD

**Issue by bagel897** [python-lsp/python-lsp-server#201]
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#progress
LSP added a progress system. Example Lua Language server:
![image](https://user-images.githubusercontent.com/57874654/164780189-a7d28248-e37a-4487-9265-229fb16b5c8c.png)
Could we implement a way to handle this for longer-running items and the overall starting of pylsp?

**Comment by ccordoba12** [comment]
Hey @bageljrkhanofemus, we don't have time for this right now. But you're welcome to send a pull request to implement that functionality.

**Comment by syphar** [comment]
This can be closed, since #236 is merged

**Comment by ccordoba12** [comment]
Right, thanks for pointing that out.
