### ISSUE TITLE
Rope completions enabled or disabled by default?

### ISSUE THREAD

**Issue by rchl** [python-lsp/python-lsp-server#209]
The code seems to indicate that rope completions are disabled by default: https://github.com/python-lsp/python-lsp-server/blob/4bffc39ca6923a007b084d13f67a8f2ea10613ad/pylsp/plugins/rope_completion.py#L16

but the documentation says that it's enabled by default: https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md

What's expected? What should be changed? I suppose that the documentation should be updated.

**Comment by ccordoba12** [comment]
That's correct. Our docs should be updated to say that Rope completions are disabled by default.

Could you open a pull request for it? Thanks!
