### ISSUE TITLE
Migrate from deprecated MarkedString to MarkupContent

### ISSUE THREAD

**Issue by krassowski** [python-lsp/python-lsp-server#21]
Both hover's `content` and completion's `documentation` return a plain string:
- in the case of hover it indicates a `MarkedString` which is explicitly deprecated in favour of `MarkupContent`
- in case of completion the use of string is not deprecated, but `MarkupContent` is allowed and would make the transition to markdown easier in the future

`MarkupContent` was added in [3.3.0 (11/24/2017)](https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#version_3_3_0) which was 4 years ago and should be safe to transition now given that most clients already support much newer versions of LSP specification (usually at least 3.14).

Updating the following function to return a dictionary complying with `MarkupContent` interface will be sufficient:

https://github.com/python-lsp/python-lsp-server/blob/26f234aca510a0be903aa70d8de6821547d0c6f2/pylsp/_utils.py#L139-L147

See https://github.com/krassowski/python-language-server/pull/4/files.

**Comment by ccordoba12** [comment]
I agree with this change, as long as it keeps returning plain text and not only Markdown.
