### ISSUE TITLE
cannot get autocompletion list for some cases when used in CudaText plugin

### ISSUE THREAD

**Issue by Alexey-T** [python-lsp/python-lsp-server#214]
Ubuntu 20 x64, Py 3.8

- install CudaText https://sourceforge.net/projects/cudatext/ with "LSP Client" plugin (in the 'Plugins / Addon Manager / Install')
- module 'cudatext' is now known to all py scripts
- variable 'ed' is inside 'cudatext'
- configure Python-LSP https://wiki.freepascal.org/CudaText_plugins#LSP_server_for_Python
- now open the source code of 'LSP Client', file `/home/user/.config/cudatext/py/cuda_lsp/util.py`
- go to line 31

```
def is_ed_visible(ed):
    gr_ed = ct.ed_group(ed.get_prop(ct.PROP_INDEX_GROUP)) ##### here
    return ed == gr_ed
```
- put caret after "ed." and see NO COMPLETIONS

But it gets completions after "ct."

**Comment by Alexey-T** [comment]
@veksha maybe you're interested. does it work for you on Windows?

**Comment by veksha** [comment]
perhaps because `ed` parameter type can be known only at runtime?
i'm not an expert with python.

I get completions with `ct.ed.`

**Comment by veksha** [comment]
@Alexey-T, try changing to:
```python
def is_ed_visible(ed: ct.Editor):
```

**Comment by Alexey-T** [comment]
Ok, I don't want to bother dev's; closing.
