### ISSUE TITLE
Refactoring to use dataclasses

### ISSUE THREAD

**Issue by jgarte** [python-lsp/python-lsp-server#218]
Hi,

Would an PR to refactor this [class](https://github.com/python-lsp/python-lsp-server/blob/e8cf8e5b160f227550574cba480e276a98248d44/pylsp/workspace.py#L31) to use dataclasses be accepted?

Just wanted to know if I could work on it.

**Comment by ccordoba12** [comment]
I'm sorry but that would add a very little gain to the project.
