### ISSUE TITLE
Add .flake8 to the discovery paths

### ISSUE THREAD

**Issue by m0wer** [python-lsp/python-lsp-server#219]
Currenlty README.md states that `flake8` configuration is looked for in `~/.config/flake8`, `setup.cfg`, `tox.ini` and `flake8.cfg`. Why isn't `.flake8` supported?

**Comment by ccordoba12** [comment]
Probably because the author of the flake8 plugin forgot to do it. But you're welcome to send us a pull request to add support for it.

**Comment by m0wer** [comment]
Is `flake8` who handles the discovery of its configuration or does `python-lsp-server` do it instead? I'm a bit confused because the README lists the files that are considewred as if `python-lsp-server` handled the discovery.

`flake8` already looks for `.flake8` so nothing to do there. If something needs to change in `python-lsp-server` to discover `.flake8` then I'll happily create a MR for that.

Cheers.

**Comment by ccordoba12** [comment]
The server does the discovery.

**Comment by lcheylus** [comment]
The documentation about Flake8 plugin is wrong : according to `pylsp/config/flake8_conf.py`, Flake8 configuration is looked for in `.flake8`, `setup.cfg` and `tox.ini` : 

```
CONFIG_KEY = 'flake8'
PROJECT_CONFIGS = ['.flake8', 'setup.cfg', 'tox.ini']
```

Moreover Flake8 4.0 does not read anymore its configuration in `~/.config/flake8` but only in `.flake8`, `setup.cfg` and `tox.ini` in a project directory (see https://flake8.pycqa.org/en/latest/user/configuration.html).
