### ISSUE TITLE
Consider using docstring_to_markdown for markdown hover and documentation

### ISSUE THREAD

**Issue by krassowski** [python-lsp/python-lsp-server#22]
Following up on the previous discussions:
- https://github.com/palantir/python-language-server/issues/760
- https://github.com/palantir/python-language-server/issues/836
 
I would like to propose the integration of [docstring-to-markdown](https://pypi.org/project/docstring-to-markdown/) which is a small converter that handles conversion of docstrings, including:
- [PEP 287](https://www.python.org/dev/peps/pep-0287/) compliant reStructuredText docstrings and [PEP 257](https://www.python.org/dev/peps/pep-0257/) compliant docstrings
- reStructuredText with common Sphinx extensions to a degree sufficient to cover majority of docstrings in popular Python projects such as numpy, pandas, or sklearn, including special cases specific to numpy documentation.
- rejects to convert ambiguous docstrings to prevent malformated text if it turns out to be using a different format; in such case the LSP server should return plain text rather than markdown (or try using a different converter)

Recognition of other docstring styles is planned. The docstring-to-markdown was successfully adopted in jedi-lanaguage-server. I also used it for quite a while on my fork without any major issues. The performance impact of doing on the flight conversion is negligible when only returning the completion in `completionItem/resolve` (https://github.com/python-lsp/python-lsp-server/pull/1, to be updated); I did not test the performance impact in other scenarios.

I would be happy to transfer the project to the python-lsp organization. Leaving this up for discussion as I am sure there will be different takes and opinions.

### Alternatives:
While docstring-to-markdown uses simple parsers and regular expressions other solutions are possible. A number of other solutions and packages was tried before I decided to develop docstring-to-markdown (see https://github.com/pappasam/jedi-language-server/issues/22#issuecomment-633257107) and it appeared the best solution at that time, however other approaches may be feasible in the future:
- converting reStructuredText to HTML and converting from HTML to Markdown
- converting reStructuredText to docutils internal nodes format and converting those to Markdown
The above approaches are likely to be more computation intensive and the first step implies building an entire documentation of a project in order to resolve references
- :heavy_plus_sign:  having the resolved references is nice because the "See also" section can be made interactive (i.e. the links work)
- :heavy_minus_sign: the added overhead may be prohibitive for performing such conversion during the runtime (too long for the user)
- :neutral_face: it is not really that important to have the links in the "See also" section in completer/hover documentation - IMO the most important piece of information is the signature, description of arguments and returned values.
- :neutral_face: it is possible to pre-build the Markdown docstrings for large, frequently used projects such as numpy, pandas etc, but this would not work for custom large codebases and may require a significant effort given the large variety of documentation tools (reStructuredText/Sphinx/MyST and extensions).

**Comment by krassowski** [comment]
Please see my reference integration [on my fork, here](https://github.com/krassowski/python-language-server/blob/3536061e43ff9486d6a7d6df7f91d10acb3920e8/pyls/_utils.py#L149-L182).

**Comment by ccordoba12** [comment]
Is it possible to send plain text and Markdown at the same time? The thing is we don't need Markdown in Spyder.

The other alternative would be to add a config option to control what format is used in the server.

**Comment by krassowski** [comment]
No, you cannot send both. A config option should not be needed either; according to the [LSP specification](https://microsoft.github.io/language-server-protocol/specification) if the client does not support a particular `MarkupKind` it should register their capabilities accordingly, using `HoverClientCapabilities.contentFormat`, `SignatureHelpClientCapabilities.documentationFormat` and `CompletionClientCapabilities.completionItem.documentationFormat` and the server should return response in the format that the client can handle:

```typescript
export interface HoverClientCapabilities {
	/**
	 * Whether hover supports dynamic registration.
	 */
	dynamicRegistration?: boolean;

	/**
	 * Client supports the following content formats if the content
	 * property refers to a `literal of type MarkupContent`.
	 * The order describes the preferred format of the client.
	 */
	contentFormat?: MarkupKind[];
}
```

```ts
export interface SignatureHelpClientCapabilities {
	/* ... */

	/**
	 * The client supports the following `SignatureInformation`
	 * specific properties.
	 */
	signatureInformation?: {
		/**
		 * Client supports the following content formats for the documentation
		 * property. The order describes the preferred format of the client.
		 */
		documentationFormat?: MarkupKind[];
                /* ... */
        }
       /* ... */
}

```

```ts
export interface CompletionClientCapabilities {
	/* ... */

	/**
	 * The client supports the following `CompletionItem` specific
	 * capabilities.
	 */
	completionItem?: {
                /* ... */

		/**
		 * Client supports the following content formats for the documentation
		 * property. The order describes the preferred format of the client.
		 */
		documentationFormat?: MarkupKind[];
                /* ... */
      }
}
```

**Comment by ccordoba12** [comment]
Ok, sounds good then
