### ISSUE TITLE
Flake8 reports wrong severity level for E999

### ISSUE THREAD

**Issue by jhossbach** [python-lsp/python-lsp-server#220]
Hey,
If I understand the [error codes](https://flake8.pycqa.org/en/latest/user/error-codes.html) in the flake8 documentation correctly, there is only one error with code E999 for general syntax errors. Is it possible to change the LSP severity level for this error to 1 instead of 2 as this is an actual error in the code?

**Comment by ccordoba12** [comment]
Hey @jhossbach, thanks for reporting. I don't know if that's possible but the configuration options for the server are [here](https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md). And the way to configure it depends on your editor or IDE.

**Comment by jhossbach** [comment]
The problem is the hardcoded `lsp.DiagnosticSeverity.Warning` in the internal flake8 plugin: https://github.com/python-lsp/python-lsp-server/blob/a9d503c5a766188628f554f53bde1116a5b58bc2/pylsp/plugins/flake8_lint.py#L192

We could add a check if the `msg` starts with an `E` and set the severity level to `lsp.DiagnosticSeverity.Error`.
I can open a pull request if you want.

**Comment by ccordoba12** [comment]
Ok, I see, sorry for the misunderstanding. We'll be glad if you can open a pull request for this.
