### ISSUE TITLE
Flake8 reports wrong severity level for code Fxxx

### ISSUE THREAD

**Issue by lcheylus** [python-lsp/python-lsp-server#230]
Flake8 uses Fxxx for error codes generated by PyFlakes, see https://flake8.pycqa.org/en/latest/user/error-codes.html and https://flake8.pycqa.org/en/latest/glossary.html#term-error-code

Currently, these error codes are reported with the **Warning** severity level by Flake8 plugin instead of **Error** level, same issue as https://github.com/python-lsp/python-lsp-server/issues/220 for E999 code.

For now, I have to keep pycodestyle, PyFlakes and McCabe plugins in my LSP client configuration instead of using Flake8 plugin, to have the correct Warning/Error codes.

**Comment by jhossbach** [comment]
You're right, it should be sufficient to include all `F` codes as errors and only consider `E999` as error. I'll make a PR for that

**Comment by lcheylus** [comment]
I'm currently pushing my PR for this issue.
