### ISSUE TITLE
Python Unicode normalization seems to not be respected

### ISSUE THREAD

**Issue by xeniagda** [python-lsp/python-lsp-server#235]
Consider the following file:
```py
identifier_j = 10
identifier_ⅉ = 20

print(identifier_j, identifier_ⅉ)
```

According to the [Normalizing identifiers section of PEP 672](https://peps.python.org/pep-0672/#normalizing-identifiers), `identifier_j` and `identifier_ⅉ` should be considered the same identifier, and when run in python3.8, outputs `20 20` as expected.

However, pylsp seems to consider these different identifiers, for example highlighting references:

<img width="278" alt="bild" src="https://user-images.githubusercontent.com/8290983/177039240-baf326c3-9b25-4c20-8fad-5e33e8c944d2.png">

Listing symbol references:

<img width="337" alt="bild" src="https://user-images.githubusercontent.com/8290983/177039252-d2c15999-2731-46c9-ab05-f8764ac3ec60.png">

Etc.

**Comment by ccordoba12** [comment]
Hey @loovjo, thanks for reporting. This project is only a wrapper around a lot of other Python projects that provide code completion, symbols, linting and much more.

For symbols we use the Jedi library, so please report your error there:

https://github.com/davidhalter/jedi
