### ISSUE TITLE
Add function objects to completions

### ISSUE THREAD

**Issue by llan-ml** [python-lsp/python-lsp-server#244]
In some cases, we might only want to use the name of a function. However, currently the function is always completed with parenthesis and parameters. An example is as follows:
![image](https://user-images.githubusercontent.com/22030149/178697408-bda7759a-1697-4507-8cbe-d391035d4036.png)

Can we add an option like `pylsp.plugins.jedi_completion.include_class_objects` to add function objects as a separate completion item?

**Comment by ccordoba12** [comment]
Hey @llan-ml, thanks for reporting. Unfortunately, we're don't have much free time to add an option for this. But you're welcome to send us a pull request that implements it.

Otherwise, I suggest to use the option `pylsp.plugins.jedi_completion.include_params` to disable parameters in completions.

**Comment by llan-ml** [comment]
Hi @ccordoba12, I create a PR #246 to add this feature.
