### ISSUE TITLE
Add alternative ways to install python-lsp-server

### ISSUE THREAD

**Issue by nougcat** [python-lsp/python-lsp-server#245]
Currently in main README file, the only way listed to install it is - through pip, which is probably fine way, but it would be great to see more clean and elegant ways to install it, like through official linux repos (for example [fedora](https://src.fedoraproject.org/rpms/python-lsp-server), [debian](https://packages.debian.org/bookworm/python3-pylsp)/deb-based OSes or [arch](https://archlinux.org/packages/community/any/python-lsp-server/)), or maybe some people on windows can install it using [conda](https://anaconda.org/conda-forge/python-lsp-server)

If i can get a permission, i can also write it myself and submit it as PR.

**Comment by ccordoba12** [comment]
Hey @nougcat, thanks for interest in wanting to help us improve our docs. You don't need write permissions to do it, simply create a fork and send us a pull request with your changes.

**Comment by jgarte** [comment]
@nougcat Can also be installed with [GNU/Guix](guix.gnu.org)

**Comment by nougcat** [comment]
@jgarte It is also available in opensuse, solus and others, but package for it is named everywhere the same (except for alpine). So i think that it only makes sens to show installation instruction only for the biggest distros, so readme won't become unnecessarily long
