### ISSUE TITLE
Flake8 Severity too high

### ISSUE THREAD

**Issue by nexplor** [python-lsp/python-lsp-server#256]
After https://github.com/python-lsp/python-lsp-server/pull/234, all Flake8 codes starting with "F" are reported with error severity. This is overly high: the only codes that really errors are F821, F823, F831, and _maybe_ F405 and F822.

Can we add explicit checks for error codes to classify them as errors vs. warnings?

**Comment by ccordoba12** [comment]
Hey @nexplor, thanks for reporting. I have no problem with that, so please submit a pull request to provide more fine-grained error reports from Flake8.

**Comment by jhossbach** [comment]
I feel troubled by this: Flake8 is really not designed to fine-grain all errors. Similar to the above, e.g. F501, F521 and F721 would need to be declared as errors. So either we carefully design the severeness of all error codes or we convince the flake8 maintainers to make the error codes more meaningful. You might consider using pycodestyle, mccabe and pyflakes separately as they support better fine-graining.

**Comment by jhossbach** [comment]
FYI `python-lsp-ruff` allows customizing of severities as of `v1.5.0` (although only on a per-code level, and it does not accept regex patterns)

**Comment by ccordoba12** [comment]
That would be a good enough solution here too. But I guess you're interested in giving us a hand with it for Flake8, right?
