### ISSUE TITLE
yapf formatting fails when pyproject.toml is in the workspace

### ISSUE THREAD

**Issue by masad-frost** [python-lsp/python-lsp-server#260]
Version: 1.5.0

Steps to reproduce:
- Create workspace with pyproject.toml
- Install pylsp with yapf
- send a format request (must include options)
- error  `formatting error: toml package is needed for using pyproject.toml as a configuration file`

I think I introduced this regression in #134.

Should we add `toml` as a requirement for `yapf` formatter like `whatthepatch`?

**Comment by ccordoba12** [comment]
Sure, I see no problem with that.
