### ISSUE TITLE
Try running pylsp script, can't output message and quit，what?

### ISSUE THREAD

**Issue by Hebe970217** [python-lsp/python-lsp-server#268]
![Screenshot_select-area_20220923183144](https://user-images.githubusercontent.com/95731817/191942481-a3c55c5b-e577-44e6-ace0-7a707f8afcca.png)

**install step**
`pip3 install git+https://github.com/python-lsp/python-lsp-server.git`  // less root

**try running**
`cd ~/.local/bin && ./pylsp --log-file ./log <init.json`

**protocol init request text**
[init.txt](https://github.com/python-lsp/python-lsp-server/files/9632913/init.txt)
need save file suffix to json

Please help！

**Comment by Hebe970217** [comment]
guess the parent procee id invalid，when I changed init request param `processId`，but it's not work so.

lanuch this, add args -v，execute result :
![Screenshot_select-area_20220923184725](https://user-images.githubusercontent.com/95731817/191944881-a1e0228f-d085-4a29-a212-73a7a6490ec1.png)

**Comment by ccordoba12** [comment]
Hey @Hebe970217, thanks for reporting. I don't understand where you get the impression that this server can be configured through stdout like you're trying to do.

This is its help:

```
usage: pylsp [-h] [--tcp] [--ws] [--host HOST] [--port PORT]
             [--check-parent-process]
             [--log-config LOG_CONFIG | --log-file LOG_FILE] [-v] [-V]

Python Language Server

optional arguments:
  -h, --help            show this help message and exit
  --tcp                 Use TCP server instead of stdio
  --ws                  Use Web Sockets server instead of stdio
  --host HOST           Bind to this address
  --port PORT           Bind to this port
  --check-parent-process
                        Check whether parent process is still alive using
                        os.kill(ppid, 0) and auto shut down language server
                        process when parent process is not alive.Note that
                        this may not work on a Windows machine.
  --log-config LOG_CONFIG
                        Path to a JSON file containing Python logging config.
  --log-file LOG_FILE   Redirect logs to the given file instead of writing to
                        stderr.Has no effect if used with --log-config.
  -v, --verbose         Increase verbosity of log output, overrides log config
                        file
  -V, --version         show program's version number and exit
```

**Comment by Hebe970217** [comment]
> 嘿@Hebe970217，感谢报道。我不明白您在哪里得到的印象是可以像您尝试做的那样通过标准输出配置此服务器。
> 
> 这是它的帮助：
> 
> ```
> usage: pylsp [-h] [--tcp] [--ws] [--host HOST] [--port PORT]
>              [--check-parent-process]
>              [--log-config LOG_CONFIG | --log-file LOG_FILE] [-v] [-V]
> 
> Python Language Server
> 
> optional arguments:
>   -h, --help            show this help message and exit
>   --tcp                 Use TCP server instead of stdio
>   --ws                  Use Web Sockets server instead of stdio
>   --host HOST           Bind to this address
>   --port PORT           Bind to this port
>   --check-parent-process
>                         Check whether parent process is still alive using
>                         os.kill(ppid, 0) and auto shut down language server
>                         process when parent process is not alive.Note that
>                         this may not work on a Windows machine.
>   --log-config LOG_CONFIG
>                         Path to a JSON file containing Python logging config.
>   --log-file LOG_FILE   Redirect logs to the given file instead of writing to
>                         stderr.Has no effect if used with --log-config.
>   -v, --verbose         Increase verbosity of log output, overrides log config
>                         file
>   -V, --version         show program's version number and exit
> ```

Sorry，I watch java(jdtls) and c++(clangd) lps can to use, it's working.
I try lanuch pylsp to stdio, this is the problem.
default mode is process stdio, it's can read and write, right?

**Comment by ccordoba12** [comment]
Sure, you can launch it in studio mode, but this server needs to be configured from the client.

**Comment by Hebe970217** [comment]
> Sure, you can launch it in studio mode, but this server needs to be configured from the client.

I tried to input my protocol file into stdin using stdio redirection symbols. It seems that it doesn't respond. Is there a problem with my protocol. Because I tried to pass an empty params, it seemed to exit directly.

I havn't frontend same vscode, cause I development a IDE for now.
I am integrating the language server of python, Maybe the easy to use method is not suitable for me, such as vscode.
I have just started to explore lsp for python. If you have any good suggestions, please let me know. I would be grateful.

**Comment by Hebe970217** [comment]
> Sure, you can launch it in studio mode, but this server needs to be configured from the client.

The client starts because it needs to add a monitor for processID. I directly specify the ProcessId of a resident process. According to normal understanding, it can still start. I don't quite understand the difference between starting from client and terminal for u said.
