### ISSUE TITLE
workspace/didChangeConfiguration should accept String or JSONObject not only dict

### ISSUE THREAD

**Issue by albilu** [python-lsp/python-lsp-server#276]
Hello,
I am using [lsp4J](https://github.com/eclipse/lsp4j) as LSP Client.
Passing configuration to pyls server: 

`DidChangeConfigurationParams params = new DidChangeConfigurationParams(new String("{\"pylsp\": {\"plugins\": {\"jedi\": {\"environment\": \"/usr/bin/python3\"}}}}"));
server.getWorkspaceService().didChangeConfiguration(params);`
                
  
Throw exeption:
2022-10-11 16:04:42,485 Romance Daylight Time - ERROR - pylsp_jsonrpc.endpoint - **Failed to handle notification workspace/didChangeConfiguration:** {'settings': '{"pylsp": {"plugins": {"jedi": {"environment": "/usr/bin/python3"}}}}'}
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Python\Python310\site-packages\pylsp_jsonrpc\endpoint.py", line 145, in _handle_notification
    handler_result = handler(params)
  File "C:\Users\xxx\AppData\Roaming\Python\Python310\site-packages\pylsp_jsonrpc\dispatchers.py", line 25, in handler
    return method(**(params or {}))
  **File "C:\Users\xxx\AppData\Roaming\Python\Python310\site-packages\pylsp\python_lsp.py", line 463**, in m_workspace__did_change_configuration
    self.config.update((settings or {}).get('pylsp', {}))
**AttributeError: 'str' object has no attribute 'get'**

It seems to me that https://github.com/python-lsp/python-lsp-server/blob/develop/pylsp/python_lsp.py#L463 needs to be enhanced to accept String or JSONObject as i d'ont think there is a way to pass java "dict" object to python

**Comment by ccordoba12** [comment]
Hey @albilu, thanks for reporting. You're welcome to send us a pull request to support json objects (I think using strings is too brittle given the amount of configurability of this server). My only requirement is that using Python dicts should remain the default.

**Comment by rchl** [comment]
I might not be getting something but I find it hard to believe that a conforming LSP client would not be able to send a plain json object over the wire... This is a basic way of communicating with LSP server.

**Comment by ccordoba12** [comment]
We really don't have time for this and things seem to be working fine without it for people using this server with different clients. So, if this is really important for the OP, we're requiring a bit of their time to add support for it.

**Comment by rchl** [comment]
My comment was directed at op's claim that it's not possible to send a json object.

Since communication goes through json layer, just sending a json object should work and get translated to python dict automatically on receive.

That said, i don't know pylsp code base but I'm guessing based on general understanding of LSP

**Comment by ccordoba12** [comment]
> My comment was directed at op's claim that it's not possible to send a json object.

Oh, sorry for the misunderstanding.

**Comment by albilu** [comment]
> My comment was directed at op's claim that it's not possible to send a json object.
> 
> Since communication goes through json layer, just sending a json object should work and get translated to python dict automatically on receive.
> 
> That said, i don't know pylsp code base but I'm guessing based on general understanding of LSP

i agree. thats was also my assumption that sending a json object would work. but when i send a json object
the settings its empty:
`DidChangeConfigurationParams params = new DidChangeConfigurationParams(new **JSONObject**("{\"pylsp\": {\"plugins\": {\"jedi\": {\"environment\": \"/usr/bin/python3\"}}}}")); server.getWorkspaceService().didChangeConfiguration(params);`

logs:
2022-10-11 16:03:07,934 Romance Daylight Time - INFO - pylsp.config.config - **Updated settings to {}**
2022-10-11 16:03:07,936 Romance Daylight Time - INFO - pylsp.config.config - Disabled plugins: .....

so unless i am doing something wrong  the json object is not being cast properly. 
I will dig a bit to see if there are examples of this

**Comment by rchl** [comment]
Check the spec https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeConfiguration

You are supposed to include your configuration within the top `settings` object.
Unless the `DidChangeConfigurationParams` class already does that in your case...

**Comment by albilu** [comment]
For Java developpers here is the way to do it:
```java
Gson create = new GsonBuilder().setObjectToNumberStrategy(ToNumberPolicy.BIG_DECIMAL).create();
            Map<String, Object> settings = create
                    .fromJson(jsonSettingsObject),
                            new TypeToken<HashMap<String, Object>>() {
                            }.getType());
Map<String, Object> paramsObject = new HashMap<>();
paramsObject.put("pylsp", settings);
DidChangeConfigurationParams params = new DidChangeConfigurationParams(paramsObject);```
            
I am closing the issue. Thanks for the help
