### ISSUE TITLE
Version requirements conflict with latest dependency versions

### ISSUE THREAD

**Issue by yurivict** [python-lsp/python-lsp-server#277]
On FreeBSD I am getting these errors:
```
pkg_resources.DistributionNotFound: The 'pyflakes<2.5.0,>=2.4.0' distribution was not found and is required by python-lsp-server
pkg_resources.DistributionNotFound: The 'mccabe<0.7.0,>=0.6.0' distribution was not found and is required by python-lsp-server
pkg_resources.DistributionNotFound: The 'flake8<4.1.0,>=4.0.0' distribution was not found and is required by python-lsp-server
pkg_resources.DistributionNotFound: The 'autopep8<1.7.0,>=1.6.0' distribution was not found and is required by python-lsp-server
```

This is because you have upper limits on versions that limit current dependency versions.

Could you please consider removing such limits, or update the package to keep dependency versions current ?

Thank you,
Yuri

**Comment by ccordoba12** [comment]
Hey @yurivict, thanks for reporting. You said:

> Could you please consider removing such limits, or update the package to keep dependency versions current ?

We don't plan to remove them, sorry. For context about our decision, please see the discussion in https://github.com/python-lsp/python-lsp-server/pull/232.
