### ISSUE TITLE
Error when using python-lsp-server in embed python.

### ISSUE THREAD

**Issue by Torso1ee** [python-lsp/python-lsp-server#278]
- WARNING - pylsp.config.config - Failed to load hook pylsp_completions: Could not get version information for 'D:\\Project\\RhinoPythonNetEditor\\RhinoPythonNetEditor.Component\\bin\\Debug\\net48\\python_env\\python.exe': InternalError("The subprocess D:\\Project\\RhinoPythonNetEditor\\RhinoPythonNetEditor.Component\\bin\\Debug\\net48\\python_env\\python.exe has crashed (EOFError('Ran out of input'), stderr=).")

**Comment by ccordoba12** [comment]
This looks like a packaging problem, so please report it to the Rhino Python net editor people.

**Comment by Torso1ee** [comment]
In fact, I am writing an editor for Rhino software. I use embed python for my editor . No problem when using installed python.

**Comment by ccordoba12** [comment]
Ok, but this doesn't seem a problem with this project but with the way is packaged.
