### ISSUE TITLE
[Question] Virtual environments?

### ISSUE THREAD

**Issue by TitaniumHocker** [python-lsp/python-lsp-server#29]
Hello!

First of all thank you guys for supporting this fork.

I'm using [neovim](https://neovim.io/) as my main code editor and right now I'm trying to migrate from [coc.nvim](https://github.com/neoclide/coc.nvim) to native _neovim_ LSP client implementation(which is still in development btw).

So, I don't figured out how to configure this language server to use executables from virtual environment instead of global scope of my system. For example from python `venv` or `pipenv`. In _coc_ It was enough just to specify configuration parameter "python.pythonPath" with the full path to the python executable file in the virtual environment and everything works fine.

Tech information above
System: Manjaro GNU/Linux
LSP Client: neovim v0.5.0-dev

**Comment by yeraydiazdiaz** [comment]
I wondered about this too, maybe I'm missing something but using Sublime Text I specify the `pylsp` executable which starts the server _in its own virtual environment_. Plugins, built-in and external, import the libraries and from that virtual environment and returns responses, however, the versions of these libraries may be different than those of the project I am working on (with the exception of `pyls-flake8` which [invokes a subprocess](https://github.com/emanspeaks/pyls-flake8/blob/44f26d9ccefd60f1e6da4d7ed150d405332c4df7/pyls_flake8/plugin.py#L118-L121)).

To be fair this is generally not a problem for most plugins since they don't change that much between versions anyway, but in other editors like PyCharm or VSCode you'll be prompted to install the missing library in your virtual environment.

Am I correct in that interpretation? Is this a problem in the design of pylsp or something that could be solved at the plugin level?

**Comment by yaegassy** [comment]
I used "coc.nvim" to create `coc-pylsp` for "verification". https://github.com/yaegassy/coc-pylsp

It is only for verification, so it is not published on npm.

Why not just detect the `pylsp` command and invoke it without determining whether it is a global or virtual environment?

If you want to use pylsp and more tools, any version at the project level, I guess the approach would be to install pylsp in a virtual environment.

**Comment by TitaniumHocker** [comment]
I can run nvim from venv shell and the language server will work file, but only if language server and `pynvim` is installed in this venv. Installing this packets for every project venv seems wasteful to me.

**Comment by yaegassy** [comment]
I have `pynvim` installed on a system global basis. However, I think it works fine in "venv". I don't think running a language server has anything to do with pynvim, but if I'm wrong, I'm sorry.

**Comment by TitaniumHocker** [comment]
I have an error if pynvim is not installed in venv:
```
No "python3" provider found. Run ":checkhealth provider"
```
May be it's only in my configuration.

**Comment by yaegassy** [comment]
This is an excerpt in my environment. No problem.

```
## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/local/bin/python3"
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python version: 3.9.5
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - INFO: $VIRTUAL_ENV is set to: /private/tmp/venvcheck/venv
  - INFO: Python version: 3.9.5
  - OK: $VIRTUAL_ENV provides :!python.
```

The pynvim thing has nothing to do with pylsp, so you can ask about it on Neovim's "gitter" or "issue".

**Comment by TitaniumHocker** [comment]
I worked some days with using separate lsp server to each venv, works fine. So, I'll close the issue. Thanks for help.

**Comment by weeman1337** [comment]
Hi @TitaniumHocker so you are installing `python-lsp-server` in every project? To me that looks like a huge overhead. Did anybody find out how to install `python-lsp-server` globally or in a separate virtualenv and point it to the project currently working on?

**Comment by meshy** [comment]
Neovim 0.5 is out now, so this is no longer just for pre-release. Installing `pylsp` in the venv feels like a hack, and is a frustrating 
step to have to repeat after rebuilding venvs.

Thankfully I'm not using a stricter python package manager that would object to the extra package.

I am still looking for a solution to this that makes it work more like my previous setup in neovim.

**Comment by ccordoba12** [comment]
We provide the option `pylsp.plugins.jedi.environment` to configure your preferred environment, so you need to make use of it (see our [configuration description file](https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md)).

Note: This is something that needs to be solved client-side, so please stop posting comments here and open an issue in Neovim or your other editors or IDEs to add support for that.

**Comment by meshy** [comment]
Apologies for the noise. Thanks for the pointer.

**Comment by apapsch** [comment]
My global `pylsp` script:

```sh
#!/bin/sh
pipenv scripts > /dev/null 2>&1 || {
    echo "run pylsp inside directory with Pipfile"
    exit 1
}
exec pipenv run pylsp "$@"
```

Please mind the hack. 🚂
