### ISSUE TITLE
Customize auto-import resolution order via directive / disable auto-import for module

### ISSUE THREAD

**Issue by nettrino** [python-lsp/python-lsp-server#297]
Hi all.
I have run into an edge-case where I am overwriting objects from an auto-generated module. So for instance, my auto-generated module (called raw.py)  defines a bunch of objects, then in my module (types.py), I do a wildcard import and overwrite whatever necessary, leaving the rest of the objects intact. What this allows me to do is use types.py across the whole codebase, but objects included in raw.py only are getting picked up by the language server using the auto-import functionality. What I would want to do is  disable importing from raw.py and instead import from types.py only. 

Is this something that could be added to the auto-import plugin? aka either prevent imports from a given module or specify resolution order?

**Comment by ccordoba12** [comment]
Hey @nettrino, thanks for reporting. @bagel897, what do you think about this one?

**Comment by bagel897** [comment]
1. You can make raw.py a private module by renaming it to _raw.py
2. Wildcard imports are not and will not be supported

**Comment by bagel897** [comment]
Is there any other ideas for this or should we close the issue?

**Comment by ccordoba12** [comment]
Let's close it given that your solution of renaming modules to be private is feasible.
