### ISSUE TITLE
`textDocument/documentSymbol` returns empty result for non-existing files

### ISSUE THREAD

**Issue by rear1019** [python-lsp/python-lsp-server#301]
`textDocument/documentSymbol` returns an empty result for non-existing files even though Jedi does provide symbol information. The culprit us the following code:

https://github.com/python-lsp/python-lsp-server/blob/0c76a528c391ba723b5b1bc1a5c34dded9bb76c4/pylsp/plugins/symbols.py#L94-L99

This can reproduced by creating a new file in Spyder: No symbol information is available in the Symbols Switcher and Outline plugin as long as the file is not saved¹. Code folding and linting does work.

¹ Note: Saving the new file is not sufficient to fix the issue in Spyder <= 5.4.0 due an another unrelated bug. See [spyder/spyder-ide#20047.](https://github.com/python-lsp/python-lsp-server/blob/0c76a528c391ba723b5b1bc1a5c34dded9bb76c4/pylsp/plugins/symbols.py#L94-L99)

EDIT: Formatting

**Comment by ccordoba12** [comment]
Hey @rear1019, thanks for reporting. What do you propose to fix the issue? Removing the try/except you referenced?

**Comment by rear1019** [comment]
I am not quite sure, but I think that `docismodule` should be determined via `pathlib.Path(document.path) == d.module_path`¹ – that is, check the file paths for equivalence. `os.path.samefile()`² actually accesses the filesystem to check if the two paths point to the same file (think of hard links on UNIX). I don’t think that’s intended here.

I can make a PR if the proposed fix is deemed correct.

¹ Or a variant thereof, depending on the required Python/Jedi compatibility.
² https://docs.python.org/3.10/library/os.path.html#os.path.samefile

**Comment by ccordoba12** [comment]
> os.path.samefile()² actually accesses the filesystem to check if the two paths point to the same file (think of hard links on UNIX). I don’t think that’s intended here.

Right, then I agree with your proposed solution. Please submit a PR for it.
