### ISSUE TITLE
Custom for pylsp style in .cfg

### ISSUE THREAD

**Issue by felrock** [python-lsp/python-lsp-server#310]
I have a specified custom style guide that I would to read into pylsp. I couldn't find an example or anything in the CONFIGURATION.md file. Any ideas?

**Comment by ccordoba12** [comment]
Hey @felrock, thanks for reporting. What's guid?

**Comment by felrock** [comment]
Hey @ccordoba12, sorry it's "style guide", like the .pycodestyle but with a specified path.

**Comment by felrock** [comment]
Adding for example a .pylintrc file somewhere

**Comment by ccordoba12** [comment]
I see. Unfortunately, it's not possible to configure pylsp like that. Options need to be passed from an LSP client to this server in json format.

**Comment by felrock** [comment]
I was able to do it with the following setup sequence

```
require('lspconfig')['pylsp'].setup{
    capabilities = capabilities,
    on_attach = on_attach,
    flags = lsp_flags,
    settings = {
      pylsp = {
        plugins = {
          pycodestyle = { enabled = false },
          autopep8 = { enabled = false },
          pydocstyle = { enabled = false },
          flake8 = { enabled = false },
          pyflakes = { enabled = false },
          pylint = {
            enabled = true,
            args = {"--rcfile=<path-to-cfg-file>"}
          }
      }
    }
  }
}
```
