### ISSUE TITLE
python 3.11 support

### ISSUE THREAD

**Issue by jhartum** [python-lsp/python-lsp-server#315]
I got this error message
pylsp: -32602: NotImplementedError: Python version 3.11 is currently not supported.

**Comment by ccordoba12** [comment]
Hey @jhartum, thanks for reporting. PyLSP is only a wrapper around a lot of code completion and linting libraries (e.g. Jedi, Pycodestyle, Pylint, etc) to make them conform to the LSP.

So, please detect in your logs what's the library that's giving you the `NotImplementedError` error you reported above and open an issue in their issue tracker about that.

**Comment by x61** [comment]
@jhartum, have you found a solution to this problem? I am facing the same issue

**Comment by jhartum** [comment]
> @jhartum, have you found a solution to this problem? I am facing the same issue

Hey!
I install some plugin(can't remember title xD) and this plugin not support new version of python, so I just delete it)

**Comment by Grant-S-Z** [comment]
I meet the same issue too.
The version of python that I am using is _Python 3.11.2_, and it tells me that "LSP :: Error from the Language Server: NotImplementedError: Python version 3.11 is currently not supported" .

**Comment by spenczar** [comment]
The source of this is the "parso" package, which parses Python files. parso is a dependency of jedi, which is a dependency of python-lsp-server.

Parso added Python 3.11 support in version 0.8.3 (https://github.com/davidhalter/parso/releases/tag/v0.8.3)

Jedi v0.17.x requires Parso<0.8, so Jedi v0.17.x effectively does not support Python 3.11. 

One tricky thing is that if you've install `python-language-server`, it depends on Jedi <=0.17.x. You want to install `python-lsp-server`, which is able to use the latest Jedi.
