### ISSUE TITLE
flake8 complains about unused imports when referenced in "type:" comment

### ISSUE THREAD

**Issue by rchl** [python-lsp/python-lsp-server#326]
Apparently flake8 v6 has [updated pyflakes](https://flake8.pycqa.org/en/latest/release-notes/6.0.0.html#new-dependency-information) from [v2 to v3](https://github.com/PyCQA/flake8/pull/1748/files) and pyflake v3 has a peculiar change:

> Remove handling of python 2.x # type: comments. Use annotations instead

which means that python 3 projects that use `type:` comments will now have a lot of linter issues about unused imports. The suggestion to use annotations is not helpful as variables can only use annotations from python 3.6 so any project that relies on older version of Python is left with no solution to this problem other than completely disabling that error.

I'm assuming that pyflakes will not re-consider this decision ([some relevant issue](https://github.com/PyCQA/pyflakes/issues/747)) so I'm not sure what could be done apart from pinning older pyflakes version.

I'm curious what others think about that.

**Comment by ccordoba12** [comment]
I don't think it is our place to "correct" that decision, much less if it's not going to be reversed. Is it not possible to ignore that linting warning?

**Comment by rchl** [comment]
Sure it's possible to ignore the warning but it's a pretty useful warning in general. The problem is with it "misfiring" in this case.

But besides that, my thinking is that if you are just running linting from CI or commit hook you can decide which version of pyflakes or flake8 to use based on the project you have so there is no problem there. For a language server like pyslp you want it to universally work on various projects though and I would think that you would want it to have as wide compatibility with various projects as possible. So requiring latest version of flake8 might not be ideal for that case.

I'm not that familiar with pypi ecosystem to know if there is a good way to handle that. Maybe there is a way to keep pylsp compatible with all versions of flake8 (maybe that's already the case?) and then let user decide which one to use.

**Comment by ccordoba12** [comment]
> I'm not that familiar with pypi ecosystem to know if there is a good way to handle that. Maybe there is a way to keep pylsp compatible with all versions of flake8 (maybe that's already the case?) and then let user decide which one to use.

Yeah, for now pylsp is compatible with flake8 5 and 6, so it's up to the user to decide which version they want to use. However, I think we'll drop support for version 5 once we move to rely on Python 3.8+ in six months or so (because older versions don't receive updates and flake8 6 depends on 3.8.1+).
