### ISSUE TITLE
Auto-import?

### ISSUE THREAD

**Issue by kuator** [python-lsp/python-lsp-server#34]
jedi doesn't support auto-import: https://github.com/pappasam/jedi-language-server/issues/126#issuecomment-835878364
can python-lsp support it through other means?

**Comment by andfoy** [comment]
@kuator, an addition in Jedi would need to be required in order to do this, there was a plan to implement a race-based completion request between Jedi and Rope, which provides auto-import and better compiled extension analysis, however it needs to be migrated to the new server

**Comment by kuator** [comment]
Quoting the original Jedi author: "Jedi does not support autoimport nor will it in the near future"  https://github.com/davidhalter/jedi-vim/issues/736#issuecomment-751416521

**Comment by ccordoba12** [comment]
I think @andfoy meant that an addition to this server is needed to support getting responses from both Jedi and Rope at the same time.

**Comment by kuator** [comment]
> I think @andfoy meant that an addition to this server is needed to support getting responses from both Jedi and Rope at the same time.

Oh, I see, I'm sorry for misunderstanding

**Comment by mlucool** [comment]
As another option, try out https://github.com/deshaw/jupyterlab-pyflyby for jupyterlab auto-import

**Comment by kuator** [comment]
@mlucool I mostly do backend, so I think it's a no-go for me, thanks for the reply though!

**Comment by Hubro** [comment]
The language server in [Pyright](https://github.com/microsoft/pyright) does this, i.e. it shows auto-complete suggestions for all functions and classes from all resolved Python modules and submodules, and if you select one it adds the import automatically. Probably a good reference point if somebody decides to implement it here.

**Comment by ccordoba12** [comment]
Pyright is done in Typescript, so it doesn't offer much help to us.

**Comment by Hubro** [comment]
> Pyright is done in Typescript, so it doesn't offer much help to us.

Yes, but I only meant to suggest it as a reference to learn from. Surely it must help to examine a working implementation and not have to figure out everything from scratch.

**Comment by mlucool** [comment]
@kuator pyflyby is pure python: https://github.com/deshaw/pyflyby ([blog](https://www.deshaw.com/research/desco-quansight-improving-jupyter-efficiency))

**Comment by Hubro** [comment]
> @kuator pyflyby is pure python: https://github.com/deshaw/pyflyby ([blog](https://www.deshaw.com/research/desco-quansight-improving-jupyter-efficiency))

Holy shit, that repo looks friggin awesome... If the performance is good it looks like the perfect basis for an auto import feature in a language server.

Actually I could probably add a save hook to automatically add missing imports. Then I'd only be missing the auto-complete suggestions.

**Comment by Yevgnen** [comment]
Any update on this? `pyflyby` looks so great.

**Comment by bagel897** [comment]
https://github.com/bageljrkhanofemus/pylsp-autoimport
relatively simple solution, formats entire document. Could be moved to this repo due to simplicity. A better solution would be to integrate it with Jedi or Rope somehow so we can let the user pick a module rather than retroactively adding them.

**Comment by ccordoba12** [comment]
Hey @bageljrkhanofemus, that's pretty cool! You could move it to this organization, so you can maintain it yourself (we wouldn't like to maintain more plugins here).

**Comment by bagel897** [comment]
How would I do that?

**Comment by ccordoba12** [comment]
I can send you an invite so you can you our organization.

**Comment by amerlyq** [comment]
@bageljrkhanofemus I dunno how to use your plugin, as despite "autoimport" being installed (and works manually), and plugin is enabled in config -- no imports are suggested for missing "Path" or added automatically. Even outside virtualenv.

@ccordoba12 as a general question -- how to ensure the order in which "formatting" applies?
Most likely we need "autoimport" -> "isort" -> "black".

**Comment by ccordoba12** [comment]
I think we're not ensuring any order right now.

**Comment by bagel897** [comment]
1. The current one corrects missing imports
2. I could add the tryfirst order suggestion, but 
a) black does the same setting and I'm pretty sure isort may do it too, so it wouldn't work.
b) I don't really like how the current one works, so wouldn't reccomend using it yet
3. I'm making a new on which suggests imports as completion suggestions
Oh also you need to install the (old) plugin, which is a pypi package into wherever you have pylsp

**Comment by bagel897** [comment]
![image](https://user-images.githubusercontent.com/57874654/163697789-571ed57c-da2e-41be-92c0-7bbb1a84cd44.png)
![image](https://user-images.githubusercontent.com/57874654/163697849-d0876ff2-31e2-41ec-8b86-fbeb56d25ab3.png)
~~Is there going to be a way to combine autoimport suggestions with Jedi suggestions?
Do you know how I'd actually insert the insert statement when the suggestion is chosen?~~
Is there any advice for how to format the documentation?
