### ISSUE TITLE
Can't find server binary file: pylsp

### ISSUE THREAD

**Issue by meiyujack** [python-lsp/python-lsp-server#341]
Kate's output tab: 
please check your PATH environment ......
https://github.com/python-lsp/python-lsp-server for the installation or info ......
BUT my pylsp is NORMAL. It can show details with "pylsp --help" in terminal.

OS: EndeavourOS (Arch series)
IDE: Kate
python-lsp-server version : v1.7.1

**Comment by ccordoba12** [comment]
Hey @meiyujack, thanks for reporting. Unfortunately, this is not something we can solve here because it's related to the integration with Kate.

So, please put in contact with its develoers so they can help you.

**Comment by meiyujack** [comment]
It's my fault. Just install python-lsp-server through pacman. Over.
