### ISSUE TITLE
Does not support match case statements from python 3.10

### ISSUE THREAD

**Issue by JasonBoyett** [python-lsp/python-lsp-server#342]
I used a match case statement in a recent program and received an invalid syntax error despite following the docs to the letter and despite the program compiling fine with python 3.11. This feature was added in 3.10 so it is relatively recent.

**Comment by ccordoba12** [comment]
@JasonBoyett, pylsp is a simply a wrapper around a lot of Python linting and code completion libraries, so we can't do anything about this.

Instead, please open an issue against the library that's giving you the error you mentioned above.

**Comment by JasonBoyett** [comment]
@ccordoba12 Thanks for the info. Any chance you could tell me how to figure out which library to submit the issue to?

**Comment by ccordoba12** [comment]
If you didn't change any of our config defaults, the message should come from Pyflakes. If not, it could be generated by Pylint or Flake8.
