### ISSUE TITLE
Failed to detect class type and provide auto-completion

### ISSUE THREAD

**Issue by ChenZhongPu** [python-lsp/python-lsp-server#349]
I installed `python-lsp-server` in NeoVim, but I found that it failed to provide auto-completion for the second dot (i.e., `reshape` method). This feature is enabled in `pyright`, and how can I enable it in `python-lsp-server`?

```python
import numpy as np
a = np.arange(15).reshape(3, 5)
```

Of course, if I added an explicit type hint for it, then it is able to support auto-completion:

```python
a: np.ndarray = np.arange(15)
b = a.reshape(3, 5)
```

**Comment by ChenZhongPu** [comment]
I know that it has something to do with **static type checking**. Will `python-lsp-server` consider add such feature?

**Comment by ccordoba12** [comment]
Hey @ChenZhongPu, thanks for reporting. Pylsp is simply a wrapper around a lot of code completion and linting Python libraries to make them conform to the Language Server Protocol. So this is a problem that can't be solved here, sorry.

Instead, please report it in the Jedi repo, which is the library we use for completions:

https://github.com/davidhalter/jedi

> I know that it has something to do with static type checking. Will python-lsp-server consider add such feature?

The support has to come from Jedi. I don't know if it can provide completions based on typing info.
