### ISSUE TITLE
Configuration tweak needed in sublime text 4

### ISSUE THREAD

**Issue by staticf0x** [python-lsp/python-lsp-server#35]
Switching `python-language-server` for `python-lsp-server` currently needs a bit more configuration in sublime text 4.
This is probably due to https://github.com/sublimelsp/LSP not shipping default config for `pylsp` yet. So when getting `pylsp` to run, one needs to add a little bit more config so the ST4 picks up when to run the `pylsp` process. See my config, `languageId` and `scopes` is what made it work:

```json
"pylsp":
{
    "enabled": true,
    "command": [
        "pylsp"
    ],
    "settings":
    {
        "pylsp":
        {
            "plugins":
            {
                "pycodestyle":
                {
                    "enabled": true,
                },
                "pyflakes":
                {
                    "enabled": false,
                },
            },
        },
    },
    "languageId": "python",
    "scopes": [ "source.python" ],
},
```

Possible config options can also be found here: https://lsp.readthedocs.io/en/latest/#python

My question is: where should this information/config be mentioned? Is this in `python-lsp-server`'s domain or rather the LSP plugin for ST4?

**Comment by andfoy** [comment]
Hi @meesha7, thanks for reaching out, however this is an issue with the Sublime Text LSP client and not with the Python-LSP-server itself, so I'm closing this one. If you want to reach out to the Sublime LSP team, please consider reopening this issue in https://github.com/sublimelsp/LSP/

**Comment by yeraydiazdiaz** [comment]
@meesha7 I wrote a [guide to setup Sublime Text 4 with Python LSP server](https://yeray.dev/python/setting-up-sublime-text-4-for-python) if you're interested

**Comment by ccordoba12** [comment]
Thanks for chiming in @yeraydiazdiaz!
