### ISSUE TITLE
installed plugins not being used

### ISSUE THREAD

**Issue by petergaultney** [python-lsp/python-lsp-server#350]
i have `pylsp_black` and `pylsp_mypy` installed, in the correct/same venv, but they're not getting used.

I have looked at your code and I don't understand how this project even knows to try to import them so they can register their hooks. Presumably something needs to run the `pylsp_mypy` script, but nothing seems to be doing that.

<img width="851" alt="Screen Shot 2023-02-19 at 11 35 48 PM" src="https://user-images.githubusercontent.com/549720/220018873-a7138727-fd09-4553-921d-6384992c13ce.png">
<img width="1552" alt="Screen Shot 2023-02-19 at 11 35 13 PM" src="https://user-images.githubusercontent.com/549720/220018892-a481a0bf-1001-4c40-b550-34334c849bbc.png">

`pylsp` is running, and you can see from its path that the other plugins are installed side by side. But nothing having to do with mypy is running.

As far as I can tell, my config has both of these plugins enabled:

```
[Trace - 11:38:51 PM] Sending notification 'workspace/didChangeConfiguration'.
Params: {
  "settings": {
    "pylsp": {
      "plugins": {
        "rope_rename": {
          "enabled": false
        },
        "autopep8": {
          "enabled": false
        },
        "yapf": {
          "enabled": false
        },
        "black": {
          "enabled": true
        },
        "rope_completion": {
          "enabled": false
        },
        "pyflakes": {
          "enabled": false
        },
        "pydocstyle": {
          "matchDir": "[^\\.].*",
          "match": "(?!test_).*\\.py",
          "enabled": true
        },
        "pycodestyle": {
          "hangClosing": false,
          "enabled": false
        },
        "pylint": {
          "enabled": false,
          "args": []
        },
        "flake8": {
          "enabled": true
        },
        "preload": {
          "enabled": true
        },
        "mccabe": {
          "threshold": 15,
          "enabled": true
        },
        "jedi_symbols": {
          "all_scopes": true,
          "enabled": true
        },
        "jedi_signature_help": {
          "enabled": true
        },
        "jedi_references": {
          "enabled": true
        },
        "jedi_hover": {
          "enabled": true
        },
        "jedi_definition": {
          "follow_builtin_imports": true,
          "follow_imports": true,
          "enabled": true
        },
        "jedi_completion": {
          "include_params": true,
          "enabled": true,
          "include_class_objects": true,
          "fuzzy": false
        },
        "jedi_rename": {
          "enabled": true
        },
        "pylsp_mypy": {
          "enabled": true,
          "live_mode": true
        },
        "pylsp_isort": {
          "enabled": true
        }
      },
      "configurationSources": [
        "flake8"
      ]
    }
  }
}
```

**Comment by petergaultney** [comment]
I do see this in the logs as well - it's the only thing i can find regarding linting.

```
[Trace - 11:51:07 PM] Received notification '$/progress'.
Params: {
  "token": "5893f6c0-5810-4e1f-a371-612fde6e82eb",
  "value": {
    "kind": "begin",
    "title": "lint: pydocstyle"
  }
}
```

is pydocstyle somehow overriding mypy's hook registration for linting?

**Comment by ccordoba12** [comment]
Hey @petergaultney, thanks for reporting. Unfortunately, this is not a problem we can help you to solve here. Instead, you need to report it in the repo of the editor or IDE you're using, so their developers can give you a hand to understand what's happening.

I can only assure you those plugins work as expected in other IDEs, e.g. Spyder.

**Comment by petergaultney** [comment]
out of curiosity, can you explain the mechanism of action for loading the plugin? does the client have to explicitly request the plugin be enabled? I wasn't able to find this documented in the repo, and I spent half an hour looking at your code to find the part where it loads plugins by name or something like that and could not find it.

**Comment by ccordoba12** [comment]
> out of curiosity, can you explain the mechanism of action for loading the plugin?

Plugins are loaded using the `pluggy` package. That's done in the `Config.__init__` method:

https://github.com/python-lsp/python-lsp-server/blob/develop/pylsp/config/config.py

> does the client have to explicitly request the plugin be enabled?

It depends on the plugin's configuration. Some are enabled by default (e.g. `python-lsp-black`) and others aren't.

**Comment by rchl** [comment]
https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md
