### ISSUE TITLE
argument --ignore: expected one argument - on the top of python file

### ISSUE THREAD

**Issue by gelerum** [python-lsp/python-lsp-server#357]
This message is written on the top of any python file in neovim:
```
usege: flake8 [options] file file ...
flake8: error: argument --ignore: expected one argument
  (flake8 ERR)
```
This message is default for flake8 command without arguments after --ignore flag.
```
> flake8 --ignore      
usage: flake8 [options] file file ...
flake8: error: argument --ignore: expected one argument
```

```
{
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.10.9",
    "system": "Linux"
  },
  "plugins": [
    {
      "plugin": "mccabe",
      "version": "0.7.0"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.9.1"
    },
    {
      "plugin": "pyflakes",
      "version": "2.5.0"
    }
  ],
  "version": "5.0.4"
}
```
I use [coc.nvim](https://github.com/neoclide/coc.nvim) , i don't definitely know whose problem it is, who is calling flake8.

**Comment by gelerum** [comment]
How can i test that the problem isn't on python-lsp-server server side?

**Comment by ccordoba12** [comment]
You need to run the server in debug mode (i.e. with the flag `-vv`). But I don't know how to set that in Neovim.
