### ISSUE TITLE
How to reduce/ignore logs coming from pylsp

### ISSUE THREAD

**Issue by garlandz-db** [python-lsp/python-lsp-server#359]
I get a lot of logs for pylsp like 
```
pylsp.config.config - Loaded pylsp plugin mccabe from <module 'pylsp.plugins.mccabe_lint' ...
...
pylsp.python_lsp - Server capabilities: {'codeActionProvider': True, 'codeLensProvide ...
```
any recommendation on how to silence them? 

Thanks!

**Comment by ccordoba12** [comment]
Hey @garlandz-db, thanks for reporting. What command are you using to start the server?

**Comment by garlandz-db** [comment]
Thanks for the pointer. I was using verbose flag which made sense. I see there's also a way to redirect it to a separate file instead of stderr which is exactly what I'm looking for. Cheers!
