### ISSUE TITLE
Unable to configure via YouCompleteMe

### ISSUE THREAD

**Issue by jtmr05** [python-lsp/python-lsp-server#363]
I've installed the `python-lsp-server` base package in addition to the optional providers that I am interested in. I proceeded to plug it into YCM as described [here](https://github.com/ycm-core/YouCompleteMe#semantic-completion-for-other-languages):
```vim
let g:ycm_language_server =
  \ [
  \   {
  \     'name': 'python',
  \     'cmdline': [ 'pylsp' ],
  \     'filetypes': [ 'python' ]
  \   }
  \ ]
```
...and it works as expected.

However, it seems that additional configuration using a [.ycm_extra_conf.py](https://github.com/ycm-core/YouCompleteMe#lsp-configuration) file is not working. I tried doing it like this:
```python
def Settings(**kwargs):
  if kwargs['language'] == 'python':
    return {
      'ls': {
         'pylsp.plugins.pycodestyle.enabled': False # disable pycodestyle
      }
    }
```

The `:YcmDebugInfo` Vim command reports such configuration is being correctly communicated to the LSP:
```
Printing YouCompleteMe debug information...
-- Resolve completions: Never
-- Client logfile: /tmp/ycm_yu9efxwd.log
-- Server Python interpreter: /usr/bin/python3
-- Server Python version: 3.10.9
-- Server has Clang support compiled in: False
-- Clang version: None
-- Extra configuration file found and loaded
-- Extra configuration path: /home/jtmr05/.ycm_extra_conf.py
-- GenericLSP completer debug information:
--   pythonCompleter running
--   pythonCompleter process ID: 28530
--   pythonCompleter executable: ['/usr/bin/pylsp']
--   pythonCompleter logfiles:
--     /tmp/pythoncompleter_stderr5d2xjsf3.log
--   pythonCompleter Server State: Initialized
--   pythonCompleter Project Directory: /home/jtmr05
--   pythonCompleter Settings: {
--   "pylsp.plugins.pycodestyle.enabled": false
-- }
[...]
```

Am I doing something wrong? Some help would be appreciated. Thanks.

**Comment by ccordoba12** [comment]
Hey @jtmr05, thanks for reporting. We don't use this server with Vim nor Neovim, so I'm afraid we can't help you with this.

Please report this problem in the YCM repo to see if they can help you.

**Comment by jtmr05** [comment]
Hey @ccordoba12, thanks for the info. I probably won't do it since I don't think it's appropriate. The truth is that there seems to exist no issue on YCM's side.
 
On another note, could you point me to what [CONFIGURATION.md](https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md) refers to as '`workspace/didChangeConfiguration`'? I reckon that may help me.

**Comment by ccordoba12** [comment]
> I probably won't do it since I don't think it's appropriate. The truth is that there seems to exist no issue on YCM's side.

Up to you but we can't offer you help about YCM, Vim or Neovim here because we simply don't use them.

> On another note, could you point me to what [CONFIGURATION.md](https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md) refers to as 'workspace/didChangeConfiguration'? I reckon that may help me.

That's the request sent from the client to the server to configure it.
