### ISSUE TITLE
Disable linting

### ISSUE THREAD

**Issue by mlucool** [python-lsp/python-lsp-server#37]
Hi,

Is it possible to use this language server and opt out of all linting?

Thanks!

**Comment by krassowski** [comment]
You can disable specific plugins:
- pylsp.plugins.pycodestyle.enabled
- pylsp.plugins.pydocstyle.enabled
- pylsp.plugins.pyflakes.enabled
- pylsp.plugins.pylint.enabled
- pylsp.plugins.mccabe.enabled

**Comment by mlucool** [comment]
Maybe I'm doing it wrong?

User settings:
```
{
    pylsp: {
      serverSettings: {
        "pylsp.plugins.pycodestyle.enabled": false,
        "pylsp.plugins.pydocstyle.enabled": false,
        "pylsp.plugins.pyflakes.enabled": false,
        "pylsp.plugins.pylint.enabled": false,
        "pyls.plugins.mccabe.enabled": false,
      }
    }
}
```

![image](https://user-images.githubusercontent.com/1813603/120503511-5cd3f100-c391-11eb-9b93-141999e9bf4f.png)

**Comment by krassowski** [comment]
Yes, you are missing "language_servers" top level key. It should be:

```json
{
    "language_servers": {
        "pylsp": {
            "serverSettings": {
                "pylsp.plugins.pycodestyle.enabled": false,
                "pylsp.plugins.pydocstyle.enabled": false,
                "pylsp.plugins.pyflakes.enabled": false,
                "pylsp.plugins.pylint.enabled": false,
                "pylsp.plugins.mccabe.enabled": false,
            }
        }
    }
}
```

It seems human brains just don't parse the example on the left correctly, see https://github.com/krassowski/jupyterlab-lsp/pull/418 - please leave a comment there on how to improve it after reading the discussion.

Also, for jupyterlab-lsp specifically you could use https://github.com/krassowski/jupyterlab-lsp/issues/585#issuecomment-830661871

**Comment by mlucool** [comment]
These both work - thanks!

I commented on krassowski/jupyterlab-lsp#418.
