### ISSUE TITLE
Go definition into a 3800 lines source code python file stuck 1-2min

### ISSUE THREAD

**Issue by txfei** [python-lsp/python-lsp-server#375]
python: 3.10.10
os: mac m1. 12.4
python manager: MiniConda
editor: vim 9.0

I use 
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
as the  vim lsp client plugin and vim-lsp-setting is a simply lsp setting plugin
i checked that i install and use pylsp for my python files

i goto definition into a python module source code class "transformers.Train",which is a 3800 lines python file

stuck for about 1-2 min,i found smaller file stuck shorter, bigger file stuck longer,  range from 10 seconds to 2 min.
what can i do to improve.

**Comment by ccordoba12** [comment]
Hey @coffee-guy, thanks for reporting. Python-lsp-server is just a wrapper around a lot of code completion and linting libraries for Python.

Go-to-definition functionality is provided by Jedi, so please report this problem to them to see if they can help you:

https://github.com/davidhalter/jedi
