### ISSUE TITLE
all linters disabled, still getting E501 error

### ISSUE THREAD

**Issue by jmwielandt** [python-lsp/python-lsp-server#382]
My config:
![imagen](https://github.com/python-lsp/python-lsp-server/assets/37153467/346b3e74-de3b-4525-8aaf-b79b424303b5)

`:LspInfo` output:
![imagen](https://github.com/python-lsp/python-lsp-server/assets/37153467/dc30bb49-56d3-4a23-94fa-dec320592179)

And still getting a E501 warning on my code.
![imagen](https://github.com/python-lsp/python-lsp-server/assets/37153467/f4a8686a-09d3-441b-8eb5-5cf2d7366c8d)

What should I do? ;-;
The on_attach function is running properly when I turn on black with null-ls.

**Comment by rchl** [comment]
The settings for plugins are at `settings.pylsp.plugins.*`, not `settings.pylsp.*`

**Comment by ccordoba12** [comment]
Yep, that's clearly stated in our [configuration main document](https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md). Closing since this is not an error in our side.
