### ISSUE TITLE
[Question] Are there any plans to create a VSCode extension for pylsp?

### ISSUE THREAD

**Issue by yaegassy** [python-lsp/python-lsp-server#39]
It would be very useful to have pylsp available for VSCode as well.

Are there any plans to create a VSCode extension for pylsp?

**Comment by ccordoba12** [comment]
No, there aren't. But thanks for your interest @yaegassy.

The thing is all people contributing to this project are not doing it for Vscode but for other editors and IDEs.

**Comment by yaegassy** [comment]
Thanks replay! I understand. 🙇

**Comment by stalkerg** [comment]
@ccordoba12 it's will be very useful because the latest Python extension not working for VSCodium and other VSCode forks.

**Comment by krassowski** [comment]
If there is someone eager to develop and maintain such an extension, I would welcome it as a separate repository in this organization - as long as it does not slow down the development and does not add a maintenance burden on the main repository. Would that work for you @ccordoba12?

**Comment by ccordoba12** [comment]
Yeah, I totally agree with that @krassowski. We don't have plans to create a VSCode extension for PyLSP, but we'll be glad to host one in our organization if people want to create and maintain it.

**Comment by yaegassy** [comment]
@stalkerg I think you can use the original `palantir/python-language-server` extension as a reference and create one for "python-lsp-server". It is very simple and should be relatively easy to create. https://github.com/palantir/python-language-server/tree/develop/vscode-client

I created an extension called `coc-pylsp` using "coc.nvim", which is a VSCode-like plugin for Vim. Please refer to it if you need it. https://github.com/yaegassy/coc-pylsp

**Comment by stalkerg** [comment]
@yaegassy thanks, yes it's definitely not so complicated a project.

**Comment by goyalyashpal** [comment]
**Edit:** 
a more recent thread: https://github.com/python-lsp/python-lsp-server/discussions/190 and https://github.com/python-lsp/python-lsp-server/discussions/176
no, seems nothing has changed

-----
hi! has anything changed for it??

this issue comment https://github.com/python-lsp/python-lsp-server/issues/156#issuecomment-1022093011 mentioned vs code so, i thouhgt...

anyhow, it's kinda mind boggling that vs code requires extension for each lsp - where other editors just have inbuild settings for lsp and just require the path to lsp to work :)
