### ISSUE TITLE
Environment path doesn't expand user directory

### ISSUE THREAD

**Issue by odiroot** [python-lsp/python-lsp-server#393]
[Previously raised](https://github.com/davidhalter/jedi/issues/1941#issuecomment-1585150875) for Jedi project but deemed irrelevant at their level.

When using Virtualenvwrapper, or just for convenience keeping all the virtual Python environments in one directory, it's not possible to
to use user home directory references in `pylsp.plugins.jedi.environment`.  E.g. `~/.virtualenvs/myenv1`.

Neither _python-lsp-server_ nor Jedi don't expand `~`. 

This is a small thing but prevents effective sharing of dev environments between users (because the username would have to be explicitly hardcoded here).

I suggest using `os.path.expanduser` in this function:

https://github.com/python-lsp/python-lsp-server/blob/297099c6afdf86dfe9a9dd9f0736b32d91a65cdc/pylsp/workspace.py#L380-L401

**Comment by ccordoba12** [comment]
Hey @odiroot, thanks for reporting. Ok, I'm fine with this suggestion, so please submit a pull request for it.

My only recommendation is to make this work only for non-Windows systems (i.e. `if not os.name == 'nt'`) because I think the tilde (`~`) doesn't map to HOME there.

**Comment by odiroot** [comment]
Hi @ccordoba12 
Thanks. According to [the documentation](https://docs.python.org/3/library/os.path.html?highlight=expanduser#os.path.expanduser), it shouldn't be breaking anything on Windows. But as you suggest, this is somewhat an unexpected thing so I can add that check.
