### ISSUE TITLE
Option for setting 'include-system-site-packages' through nvim config

### ISSUE THREAD

**Issue by PantomInach** [python-lsp/python-lsp-server#402]
## Underlying Issue with fix
I had issues with my lsp in nvim not loading information about locally installed python modules. By setting the option `include-system-site-packages` to `ture` in the `pyvenv.cfg` file from `.local/share/nvim/mason/packages/python-lsp-server/venv` this issue was resolved. Now all information about the modules is available to the lsp.

## Question
Is there an option that can be set in the nvim configuration for the pylsp to ensure that this value is always set to `true`, or is there a feasible solution to my issue?

## Additional Infos
- Using current version of [nvim-lspconf](https://github.com/neovim/nvim-lspconfig) and [nvim-cmp](https://github.com/hrsh7th/nvim-cmp)
- pylsp settings: `require('lspconfig').pylsp.setup{}`

**Comment by ccordoba12** [comment]
> Is there an option that can be set in the nvim configuration for the pylsp to ensure that this value is always set to true, or is there a feasible solution to my issue?

Unfortunately, we (i.e. the maintainers of this repo) don't use Neovim. So, I'm afraid you'll have to ask this question in another place because we can't help you with it.

**Comment by xulongwu4** [comment]
@PantomInach, see [this comment](https://github.com/williamboman/nvim-lsp-installer/issues/374#issuecomment-1003708915)
