### ISSUE TITLE
Add code action for implementing auto-import

### ISSUE THREAD

**Issue by eyalk11** [python-lsp/python-lsp-server#403]
Hi,
while the auto-import feature is great, it is not enough. And a code action to do import of a certain class from module could be a very good improvement.

**Comment by eyalk11** [comment]
FYI, there is a vim plugin called `NayvyImports` that does it basically. But it is less good.

**Comment by eyalk11** [comment]
Any response? I wasn't clear enough?

**Comment by krassowski** [comment]
Feel free to submit a pull request. If you need some inspiration, code actions are already implemented in pylsp-ruff.

**Comment by tkrabel-db** [comment]
FYI: I'm ready to tackle this. I think about the following:
- add the `pylsp_code_actions` hook to `rope_autoimport`
- define the `settings` a bit differently: `memory` for example is a shared field between `completions` and `quickfix`

I think about redefining settings to:

```python
@hookimpl
def pylsp_settings() -> Dict[str, Dict[str, Dict[str, Any]]]:
    # Default rope_completion to disabled
    return {
        "plugins": {
            "rope_autoimport": {
                "memory": False,
                "completions": {
                    "enabled": False, 
                },
                "code_actions": {
                    "enabled": False,
                },
            }
        }
    }
```

@krassowski @ccordoba12 changing the settings name likely means a major release, right? I'd really keep code actions and completions under the single rope_autoimport file as both share a lot of functionalities.

**Comment by ccordoba12** [comment]
> changing the settings name likely means a major release, right?

Not major but minor, i.e. from 1.8.x to 1.9.0

> I'd really keep code actions and completions under the single rope_autoimport file as both share a lot of functionalities.

Sounds good to me.

**Comment by Lewenhaupt** [comment]
How do I enable this? I've tried both the config above (adapted to lua) and the config in the readme but I get no code-action alternative to import.

**Comment by tkrabel-db** [comment]
@Lewenhaupt can you explain exactly what you did? 

I use this when sending the `initialize` message and it works

```javascript
export const INITIALIZATION_OPTIONS = {
  pylsp: {
    plugins: {
      rope_autoimport: {
        memory: false,
        enabled: true,
        code_actions: { enabled: true },
        completions: { enabled: false },
      },
    },
  },
};
```

**Comment by Lewenhaupt** [comment]
This is my current config. I'm using NVChad as my base config.
```
lspconfig.pylsp.setup({
	on_attach = on_attach,
	capabilities = capabilities,
	flags = {
		debounce_text_changes = 200,
	},
	settings = {
		plugins = {
			rope_completion = { enabled = true },
			rope_autoimport = {
				enabled = true,
			},
		},
	},
})
```

**Comment by tkrabel-db** [comment]
Does actvating any other plugin work? E.g. can you enable flake8?

**Comment by Lewenhaupt** [comment]
I'll check tonight 👍
