### ISSUE TITLE
Clean up unit tests

### ISSUE THREAD

**Issue by tkrabel-db** [python-lsp/python-lsp-server#410]
Follow up for #389. It makes sense cleaning up the unit tests in `test_notebook_document.py` and `test_language_server.py`, e.g. wrt shared objects.
CC @ccordoba12

**Comment by ccordoba12** [comment]
Please try to address this after PR #389 is merged so we don't have the tests in those two files growing apart too much.

**Comment by tkrabel-db** [comment]
Will do.
