### ISSUE TITLE
PyPI readme is outdated, recommends python-language-server

### ISSUE THREAD

**Issue by kparal** [python-lsp/python-lsp-server#45]
I followed the instructions in the [README on PyPI](https://pypi.org/project/python-lsp-server/), which says:

> Installing these plugins will add extra functionality to the language server:
>     pyls-mypy Mypy type checking for Python 3

After installing `pyls-mypy`, it pulls in `python-language-server` (instead of using `python-lsp-server`) and downgrades `jedi`. This can confuse many people. Just by accident, I also read the README here on github, which instead says:

> Installing these plugins will add extra functionality to the language server:
>    mypy-ls: MyPy type checking for Python 3.

which correctly uses `python-lsp-server`.

I guess there will be even more differences than the one mentioned. It might be a good idea to update the README on PyPI?

**Comment by ccordoba12** [comment]
Hey @kparal, thanks for reporting. This was fixed in PR #32 and the Readme will be fixed once we upload a new version to PyPI (which will happen soon).
