### ISSUE TITLE
notebookDocumentSync notebookSelector type error

### ISSUE THREAD

**Issue by xueerli** [python-lsp/python-lsp-server#453]
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#notebookDocumentSyncOptions

The notebookSelector should be an array type. But now the object is returned.
![image](https://github.com/python-lsp/python-lsp-server/assets/35445052/77c8f038-45ed-4c0c-a9c5-59940a399e8d)

**Comment by ccordoba12** [comment]
Hey @xueerli, thanks for reporting. Although the LSP docs are not so clear about it, taking a look at the [Python implementation](https://github.com/microsoft/lsprotocol) of the protocol, I think you're right:

https://github.com/microsoft/lsprotocol/blob/3371f9ecc1b3ad952d9757c27562b3ea4dcc1381/packages/python/lsprotocol/types.py#L6709-L6740

https://github.com/microsoft/lsprotocol/blob/3371f9ecc1b3ad952d9757c27562b3ea4dcc1381/tests/python/test_cattrs_special_cases.py#L270-L280

@smacke, could you take a look at this one? Thanks!

**Comment by smacke** [comment]
Looks like a bug; https://github.com/python-lsp/python-lsp-server/pull/454 should fix.
