### ISSUE TITLE
rope_autoimport doesn't initialize after `workspace/didChangeConfiguration` message

### ISSUE THREAD

**Issue by tkrabel-db** [python-lsp/python-lsp-server#460]
It seems the supported way to change configurations as per the LSP is to send `workspace/didChangeConfiguration`, and that is what `python-lsp-server` supports ([source](https://github.com/python-lsp/python-lsp-server/blob/develop/pylsp/python_lsp.py#L764-L770)). 

## The problem
`rope_autoimport` needs to create an index of the python modules, and it only does so when enabled at server startup. When enabling it dynamically at runtime, it doesn't do so. This is especially is an issue when using the `memory = True` setting.

## One solution
I propose extending the [hookspecs](https://github.com/python-lsp/python-lsp-server/blob/develop/pylsp/hookspecs.py) to add a hook `pylsp_workspace_configuration_changed` and to implement that hook in `rope_autoimport`, like [this one](https://github.com/python-lsp/python-lsp-server/blob/develop/pylsp/plugins/rope_autoimport.py#L238-L240).

**Comment by ccordoba12** [comment]
Fixed by #461.
