### ISSUE TITLE
Considering pointing to python-lsp-isort rather than pyls-isort in the README

### ISSUE THREAD

**Issue by doolio** [python-lsp/python-lsp-server#478]
[python-lsp-isort](https://github.com/chantera/python-lsp-isort) follows `pylsp`'s configuration convention.

`pylsp.plugins.isort.enabled`
`pylsp.plugins.isort.profile` etc.

vs

`pylsp.plugins.pyls_isort.enabled`
`pylsp.plugins.pyls_isort.profile` etc.

I had raised [pyls-isort/issue#16](https://github.com/paradoxxxzero/pyls-isort/issues/16) and [python-lsp-isort/issue#1](https://github.com/chantera/python-lsp-isort/issues/1) respectively.

**Comment by ccordoba12** [comment]
Hey @doolio, thanks for reporting. I agree with this change, so you're welcome to submit a pull request to do it.
