### ISSUE TITLE
Target date of new release?

### ISSUE THREAD

**Issue by tkrabel-db** [python-lsp/python-lsp-server#484]
@krassowski @ccordoba12 do you have an ETA for a new release? I am asking because we at Databricks could use the new Autoimport feature for our notebooks.

If there are some issues you'd like to have addressed before, I am happy to help!

**Comment by krassowski** [comment]
Is two days ago a good answer?

https://github.com/python-lsp/python-lsp-server/releases/tag/v1.9.0

**Comment by ccordoba12** [comment]
Yep, that's correct. Sorry for not letting you know about it but you can get notifications for new releases on your GitHub news feed by starring the repo.
