### ISSUE TITLE
Increase indent level after a colon was typed

### ISSUE THREAD

**Issue by ghost** [python-lsp/python-lsp-server#489]
Often in Python, when a colon is typed, the next line is indented (e.g. with `for`, `if`, `def`, `while`, `class`). It would be cool if the next line after that line would be indented.

**Comment by ccordoba12** [comment]
Hey @gregorni, thanks for reporting. That is more of an editing operation than a code completion, formatting or linting one. And the latter ones are the operations this server is in charge of.

So, I recommend you to open this issue in the editor or IDE you use with this server.

**Comment by ghost** [comment]
Okay, will do. Thanks for pointing me there!
