### ISSUE TITLE
Short question: Is python-lsp-server shipped with telemetry?

### ISSUE THREAD

**Issue by PhilippFeO** [python-lsp/python-lsp-server#492]
Hey guys,

the title says it all.

If it has some sort of telemetry, how can I disable it?

Thank you for developing and maintaining the lsp server!

**Comment by ccordoba12** [comment]
Hey @PhilippFeO, thanks for reporting. No, this server doesn't collect any telemetry.

**Comment by ccordoba12** [comment]
> Thank you for developing and maintaining the lsp server!

And thanks for your kind words!
