### ISSUE TITLE
Is pylint not supported?

### ISSUE THREAD

**Issue by Hubro** [python-lsp/python-lsp-server#50]
README.md doesn't mention pylint, but the neovim LSP log shows output from pylsp saying that the pylint entry point failed to load. When I install pylint, that error message goes away. That makes me think pylint is supported, but I can't seem to get any error messages from pylint.

Is pylint supported? If so, how come I can't get it to produce any messages?

**Comment by rchl** [comment]
It is supported. There is this plugin file for it: https://github.com/python-lsp/python-lsp-server/blob/develop/pylsp/plugins/pylint_lint.py

I guess the readme should be updated.

**Comment by Hubro** [comment]
@rchl Is there any extra configuration required for pylint? Mypy (with `pylsp-mypy`), pycodestyle and pyflakes all worked by default, but not pylint:

```
def _test() -> None:
    thisIsDefinitelyAnInvalidVariableName = "foo"
```

```
∷ pylint test.py
************* Module test
test.py:2:4: C0103: Variable name "thisIsDefinitelyAnInvalidVariableName" doesn't conform to snake_case naming style (invalid-name)
```

This produces nothing in my editor.

**Comment by Hubro** [comment]
Aha, I'm onto something

```python
@hookimpl
def pylsp_settings():
    # Default pylint to disabled because it requires a config
    # file to be useful.
    return {'plugins': {'pylint': {
        'enabled': False,
        'args': [],
        # disabled by default as it can slow down the workflow
        'executable': None,
    }}}
```

**Comment by Hubro** [comment]
@rchl I am trying to figure out how I add configuration for python-lsp. The README is referring to "your LSP configuration", and it's mentioning specific config options likg `pylsp.configurationSources` and `pylsp.plugins.pydocstyle.enabled`, but it says absolutely nothing about where to place these options. What is the config file name? Format? Where is it located?

The command's help output doesn't mention anything about configuration either:

```
➜ pylsp --help
usage: pylsp [-h] [--tcp] [--host HOST] [--port PORT] [--check-parent-process]
             [--log-config LOG_CONFIG | --log-file LOG_FILE] [-v] [-V]

Python Language Server

optional arguments:
  -h, --help            show this help message and exit
  --tcp                 Use TCP server instead of stdio
  --host HOST           Bind to this address
  --port PORT           Bind to this port
  --check-parent-process
                        Check whether parent process is still alive using os.kill(ppid, 0) and auto shut down
                        language server process when parent process is not alive.Note that this may not work on
                        a Windows machine.
  --log-config LOG_CONFIG
                        Path to a JSON file containing Python logging config.
  --log-file LOG_FILE   Redirect logs to the given file instead of writing to stderr.Has no effect if used with
                        --log-config.
  -v, --verbose         Increase verbosity of log output, overrides log config file
  -V, --version         show program's version number and exit
```

**Comment by Hubro** [comment]
Ok I'm starting to think I'm supposed to configure pylsp by passing configuration from the LSP client, which in my case is the built in language server in neovim 0.5.0 configured with `nvim-lspconfig`:

```lua
require'lspconfig'.pylsp.setup{
    settings = {
        ...
    },
}
```

I can't figure out what to put in there though. So far I have tried:

```lua
require'lspconfig'.pylsp.setup{
    settings = {
        plugins = {
            pylint = {
                enabled = true,
            }
        }
    },
}
```

and

```lua
require'lspconfig'.pylsp.setup{
    settings = {
        'plugins.pylint.enabled' = true,
    },
}
```

Without any success. That last one is even a syntax error...

**Comment by Hubro** [comment]
Ah ok, I figured it out:

```lua
require'lspconfig'.pylsp.setup{
    settings = {
        pylsp = {
            plugins = {
                pylint = {
                    enabled = true,
                }
            }
        }
    }
}
```

**Comment by Magicrafter13** [comment]
@Hubro  I don't know if something has changed but this doesn't work for me, despite pylint being in my path and giving me some warnings on the file I'm testing with (from the command line, not neovim):
```lua
-- Setup language servers.
local lspconfig = require('lspconfig')
lspconfig.pylsp.setup {
	settings = {
		pylsp = {
			plugins = {
				autopep8 = {
					enabled = true
				},
				flake8 = {
					enabled = true
				},
				pylint = {
					enabled = true
				}
			}
		}
	}
}
```
Also despite what you and the official docs show, the following actually works for me, for `flake8` at least, but still not `pylint` (idk about the other one):
```lua
-- Setup language servers.
local lspconfig = require('lspconfig')
lspconfig.pylsp.setup {
	plugins = {
		autopep8 = {
			enabled = true
		},
		flake8 = {
			enabled = true
		},
		pylint = {
			enabled = true
		}
	}
}
```

Sorry to bump an old issue like this, but I figure you still have a working setup unless you've stopped using NeoVim and/or nvim-lspconfig...

Edit:
I was wrong, the bottom portion doesn't work. It only "works" because it doesn't actually set the config values properly so nvim-lspconfig uses all default values (effectively the same as `lspconfig.pylsp.setup {}`), so whatever warning I thought was coming from flake8 was actually from default pylsp settings... And when I actually enable plugins, nothing works at all.

Edit 2:
Nevermind, sorry for bothering everyone. The issue is with the `flake8` plugin it seems, and that causes *everything* to stop working. Pylint works fine.
