### ISSUE TITLE
Release 1.10.0

### ISSUE THREAD

**Issue by tkrabel-db** [python-lsp/python-lsp-server#512]
@krassowski @ccordoba12 do you have an ETA for a new release? :)

**Comment by tkrabel-db** [comment]
CC @gabrielng-db

**Comment by ccordoba12** [comment]
Hey @tkrabel-db, sorry for the big delay in answering. I'm going to publish a new release later today.

**Comment by ccordoba12** [comment]
Release is on PyPI now:

https://pypi.org/project/python-lsp-server/1.10.0/

Thanks for your patience!
