### ISSUE TITLE
disable all parsing and linting / make a code segment "invisible" to the server

### ISSUE THREAD

**Issue by jerabaul29** [python-lsp/python-lsp-server#522]
Hi :)

Many thanks for an awesome project.

Is there a way (if so can you point to this, as I searched a bit but did not find it) / if not could the following functionality be added:

- making it possible to command the lsp server to completely ignore a series of lines.

For example, I have a setting in which some ipython magics are in my .py file, and I would like to ignore these altogether from the lsp parser and linter point of view:

![Screenshot from 2024-01-26 12-50-01](https://github.com/python-lsp/python-lsp-server/assets/8382834/d500392a-23d7-433b-a133-e8752798fee0)

Any way to get this to work, i.e. to not send these lines to the lsp / ask the lsp to ignore them altogether / catch and discard all lsp feedback on these lines? :)

**Comment by ccordoba12** [comment]
Hey @jerabaul29, thanks for reporting. That depends on the linter you're using (i.e. flake8, ruff, pylint, etc). For pylint it involves doing what you already did, but it seems you have another linter enabled.

For flake8 (and I guess for ruff too), you need to add an inline comment at the end of the line you want to skip from the linter like this

```python
%reset -f  # noqa
```
