### ISSUE TITLE
Go to definition doesn't work on modules?

### ISSUE THREAD

**Issue by fishBone000** [python-lsp/python-lsp-server#549]
I'm using nvim, NvChad to be more specific.  
I can "go to definition" on functions, variables e.t.c., but it doesn't work on modules. I expect the lsp to guide me to the source code of modules.  

I don't know if pylsp doesn't support this, or there's something wrong with my config?  
I am willing to dig down for troubleshooting. Thanks!

**Comment by Abishevs** [comment]
probably depends? Trying out this lsp rn. I have an module installed in editable mode by its relative path. So it can find modules within the parent but not in my localy installed module. 

It doesn't work for any module?

**Comment by fishBone000** [comment]
UGHHHH, further testing shows that I forgot to do `conda activate` before I start my nvim. Now `pylsp` leads me to the modules' source code.  

Perhaps add warning if going to definition of a module which is not found?

**Comment by Abishevs** [comment]
Pretty sure the error is that nothing happens :D which means its not found, sometimes "No information available" comes up in prompt line. But thats a feature of hover inline definitions (I think)

**Comment by fishBone000** [comment]
Hmmm I think you are right, I tested with clangd and lua_ls, both don't show error message when definition not found.  
Closing this issue.
