### ISSUE TITLE
Is emanspeaks/pyls-flake8 the preferred plugin for flake8 linting?

### ISSUE THREAD

**Issue by GerardoGR** [python-lsp/python-lsp-server#55]
Hi :wave: 
From reading the [3rd-party plugins section](https://github.com/python-lsp/python-lsp-server#3rd-party-plugins), it seems that the preferred method to lint with `flake8` is by installing the https://github.com/emanspeaks/pyls-flake8 plugin. On the other hand I see there is already a flake8 plugin in this repo: [pylsp/plugins/flake8_lint.py](https://github.com/python-lsp/python-lsp-server/blob/develop/pylsp/plugins/flake8_lint.py). Which one should I use?

If the [pylsp/plugins/flake8_lint.py](https://github.com/python-lsp/python-lsp-server/blob/develop/pylsp/plugins/flake8_lint.py) plugin is the preferred one. I can send a PR to update the [CONFIGURATION.md](https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md) to enable flake8 linting, e.g:

| **Configuration Key** | **Type** | **Description** | **Default** 
|----|----|----|----|
| `pylsp.plugins.flake8.enabled` | `boolean` | Enable or disable the plugin. | `true` |

**Comment by krassowski** [comment]
I don't think a motion of "preferred" plugin exist. Please note that the builtin `flake8_lint.py` plugin is disabled by default:

https://github.com/python-lsp/python-lsp-server/blob/87b76d791dc3fd2e2f229c7f8c4898ce06c352e9/pylsp/plugins/flake8_lint.py#L20

So the default value should be `false`. It seems that it is indeed missing from the `schema.json` file; please feel free to submit a PR to update the schema and update the OCNFIGURATION.md using the schema file (see https://github.com/python-lsp/python-lsp-server#development).
