### ISSUE TITLE
I find that pymongo completion is very slow - is there a way to cache this? 

### ISSUE THREAD

**Issue by cmorgan** [python-lsp/python-lsp-server#56]
I notice that libraries like numpy and others are pre-cached for the completion and API exploration, is it possible to do this for other libraries?
Thanks

**Comment by krassowski** [comment]
This is a good point for #26.

**Comment by krassowski** [comment]
I added an option to customise the list of libraries for which the labels should be cached in #26, but as for the internal caching that Jedi does on its side (https://github.com/davidhalter/jedi/blob/master/jedi/inference/helpers.py#L194-L202) I think that you would need to open an issue in the Jedi repository: https://github.com/davidhalter/jedi.

**Comment by cmorgan** [comment]
great stuff, thanks for this! Will open Jedi issue, in the short term i'll monkey patch "helpers.is_big_annoying_library"
Cheers
