### ISSUE TITLE
Pylsp not loading active environment

### ISSUE THREAD

**Issue by stabldev** [python-lsp/python-lsp-server#571]
I've pylsp and pylint plugin configured on doomemacs.
and [envrc](https://github.com/purcell/envrc) installed.
`.envrc`
```
export VIRTUAL_ENV=.venv
layout python
```
after sync and lsp-workspace-restart:
I stiil see this pylint error:
`[import-error] Unable to import <package>`

Is this because pylsp is not recognizing active environment, or?
Im really confused.....

**Comment by stabldev** [comment]
### FIXED
There was a conflict b/w pylsp pyls

**Comment by ilan-schemoul** [comment]
Can you please provide the steps you've taken to addres this issue. This has caused me to spend many hours, many times, over the course of multiple months.

**Comment by stabldev** [comment]
hi @ilan-schemoul, I feel you, but I dont quite remember that,  sorry. I think I had two lsp implementation of python installed in my system, [pyls](https://github.com/palantir/python-language-server) and [pylsp](https://github.com/python-lsp/python-lsp-server), they are different, which caused the conflict I believe. Check if you've any conflict like this. If so, keep this pylsp one.
I moved to pyright few months ago, so...
anyway, hope this helps and good luck :)
