### ISSUE TITLE
permission to push branches

### ISSUE THREAD

**Issue by agserrano3** [python-lsp/python-lsp-server#580]
Hi there,
I work with @bagel897, and I would love to get permissions to push branches to the repo so I can open pull requests. Our main objective is to work on code quality and the automatization of the search and fix of issues.
Thanks!
CC: @gatesn @ccordoba12

**Comment by krassowski** [comment]
The usual contribution flow would be forking the repository and opening pull requests from your own fork.

**Comment by agserrano3** [comment]
awesome! thanks for the info.
