### ISSUE TITLE
where to store the pylsp configuration file?

### ISSUE THREAD

**Issue by bastienboutonnet** [python-lsp/python-lsp-server#61]
I'm a bit puzzled as to where to store the configuration file of the default options of pyslp?

From the documentation I can only see where flake8 and pycodestyle configs are sourced from but I can't figure out where I should be storing (and modifying pylsp configs itself for things such as the default linter etc).

I'm really sorry if this seems like a ridiculous question. It's my first time trying to set this up and I've googled for a few hours without much luck so far.

**Comment by krassowski** [comment]
This depend on the editor you use. It is the job of the editor/IDE to send configuration to the LSP server.

**Comment by ccordoba12** [comment]
Yeah, configuration needs to be passed from the client to the server, so it can't be set here.

**Comment by bastienboutonnet** [comment]
@krassowski @ccordoba12 thanks for getting back to me it would be used in neovim.

**Comment by ccordoba12** [comment]
Ok, then you need to find a plugin that uses this server in Neovim and ask there how to configure it.

**Comment by bastienboutonnet** [comment]
@ccordoba12 ok I'll check on the `nvim-lspconfig` repo. 

I'll close the issue here. Thanks for the pointers!
