### ISSUE TITLE
Compatibiity with LanguageClient-neovim

### ISSUE THREAD

**Issue by sh34v3** [python-lsp/python-lsp-server#70]
Reading over the [previous repository](https://github.com/palantir/python-language-server) which has since been described as [deprecated](https://github.com/palantir/python-language-server/issues/935). The documentation says this lsp requires [jedi](https://github.com/davidhalter/jedi) to function, along with some adding support for other lsp client given some reqs are installed. I'm wondering if anyone has any insight on achieving support with LanguageClient-neovim? I really would rather not have multiple lsp clients installed.

**Comment by ccordoba12** [comment]
Hey @hunt0x3r, thanks for reporting. Unfortunately, we can't help you with that here because that depends on how things are implemented in LanguageClient-neovim, which we know nothing about, sorry.
