### ISSUE TITLE
No autocompletion for fastapi

### ISSUE THREAD

**Issue by quantum-booty** [python-lsp/python-lsp-server#81]
I am using nvim built-in lsp and nvim-cmp, looks like the pylsp is working for other libraries but has no autocompletion for fastapi. (Image shows that nothing happens after pressing dot)
![image](https://user-images.githubusercontent.com/28958399/132108152-8f225005-8fa9-451b-980c-cd3b62f66f87.png)
```
import fastapi
fastapi.
```
Where as pyright works:
![image](https://user-images.githubusercontent.com/28958399/132108201-3346c71f-2623-4201-8bdc-77873776f12a.png)

**Comment by ccordoba12** [comment]
Hey @quantum-booty, thanks for reporting. Please open an issue about this in the Jedi repo: https://github.com/davidhalter/jedi

Regarding code completion, this project is a tiny wrapper around Jedi. So if Jedi can't provide code completions for FastAPI, there's nothing we can do about it.
