### ISSUE TITLE
[help] How can I bypass `__getattr__()` to jump into function?

### ISSUE THREAD

**Issue by avatar-lavventura** [python-lsp/python-lsp-server#92]
In order to prevent `circular import` I have following solution. 

`cfg.py`:
```python
class EBB:
    def __init__(self):
        self.my_object = None

    def __getattr__(self, name):
        if not self.my_object:
            from project.Contract import Contract
            self.my_object: "Contract" = Contract()

        return getattr(self.my_object, name)

Ebb = EBB()
```

---------

In an another file when I do:

```python
import cfg
cfg.Ebb.my_object.account_id_to_address()  # can jump into the function.
cfg.Ebb.account_id_to_address()  # cannot jump into the function.
```

---

Here is it possible to bypass `__getattr__()` to get the object typing and jump into its functions. 

I am able to jump into `account_id_to_address` function for `cfg.Ebb.my_object.account_id_to_address() `, but I am unable to jump into `account_id_to_address` fuction for `cfg.Ebb.account_id_to_address()` due to following error  `No definitions found for: account_id_to_address`.

Here would it be possible to force `lsp` to detect the corresponding functions by checking the `__getattr__()` of the object?

**Comment by ccordoba12** [comment]
Hey @avatar-lavventura, thanks for reporting. This project is just a wrapper around Jedi, so if Jedi can't find definitions for your code, we can't do it either.

So, please report your problem here:

https://github.com/davidhalter/jedi

**Comment by avatar-lavventura** [comment]
I have solved this by trick `python-lsp` or `jedi` by using `global` keyword.

```python
def __getattr__(self, name):
    if not self.my_object:
        from project.Contract import Contract
        global Ebb
        self.my_object: "Contract" = Contract()
        Ebb = self.my_object

    return getattr(self.my_object, name)
```
